In [1]:
import numpy as np
import os
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
vectorizer = TfidfVectorizer()

In [3]:
documents = [
    "Vapour, Bangalore has a really great terrace seating and an awesome view of the Bangalore skyline",
    "The beer at Vapour, Bangalore was amazing. My favorites are the wheat beer and the ale beer.",
    "Vapour, Bangalore has the best view in Bangalore.",
]
vectorizer.fit_transform(documents)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34 stored elements and shape (3, 25)>

In [4]:
vectorizer.get_feature_names_out()

array(['ale', 'amazing', 'an', 'and', 'are', 'at', 'awesome', 'bangalore',
       'beer', 'best', 'favorites', 'great', 'has', 'in', 'my', 'of',
       'really', 'seating', 'skyline', 'terrace', 'the', 'vapour', 'view',
       'was', 'wheat'], dtype=object)

In [5]:
tfidf_model = vectorizer.fit_transform(documents)

In [6]:
tfidf_model.shape

(3, 25)

In [7]:
from IPython.display import display

pd.DataFrame(tfidf_model.toarray(), columns=vectorizer.get_feature_names_out())

,ale,amazing,an,and,are,at,awesome,bangalore,beer,best,...,of,really,seating,skyline,terrace,the,vapour,view,was,wheat
0,0.000000,0.000000,0.290764,0.221134,0.000000,0.000000,0.290764,0.343460,0.000000,0.000000,...,0.290764,0.290764,0.290764,0.290764,0.290764,0.171730,0.171730,0.221134,0.000000,0.000000
1,0.216091,0.216091,0.000000,0.164342,0.216091,0.216091,0.000000,0.127627,0.648272,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.382880,0.127627,0.000000,0.216091,0.216091
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.515544,0.000000,0.436446,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.257772,0.257772,0.331928,0.000000,0.000000

In [12]:
reviews = []
training_data = os.path.abspath("../../imdb/train/pos")
for f in os.listdir(training_data):
    if f.endswith(".txt"):
        with open(os.path.join(training_data, f), "r") as file:
            reviews.append(file.read())

In [25]:
print("\n\n*****\n".join([x for x in reviews[:3]]))

For a movie that gets no respect there sure are a lot of memorable quotes listed for this gem. Imagine a movie where Joe Piscopo is actually funny! Maureen Stapleton is a scene stealer. The Moroni character is an absolute scream. Watch for Alan "The Skipper" Hale jr. as a police Sgt.

*****
Bizarre horror movie filled with famous faces but stolen by Cristina Raines (later of TV's "Flamingo Road") as a pretty but somewhat unstable model with a gummy smile who is slated to pay for her attempted suicides by guarding the Gateway to Hell! The scenes with Raines modeling are very well captured, the mood music is perfect, Deborah Raffin is charming as Cristina's pal, but when Raines moves into a creepy Brooklyn Heights brownstone (inhabited by a blind priest on the top floor), things really start cooking. The neighbors, including a fantastically wicked Burgess Meredith and kinky couple Sylvia Miles & Beverly D'Angelo, are a diabolical lot, and Eli Wallach is great fun as a wily police detective. The movie is nearly a cross-pollination of "Rosemary's Baby" and "The Exorcist"--but what a combination! Based on the best-seller by Jeffrey Konvitz, "The Sentinel" is entertainingly spooky, full of shocks brought off well by director Michael Winner, who mounts a thoughtfully downbeat ending with skill. ***1/2 from ****

*****
A solid, if unremarkable film. Matthau, as Einstein, was wonderful. My favorite part, and the only thing that would make me go out of my way to see this again, was the wonderful scene with the physicists playing badmitton, I loved the sweaters and the conversation while they waited for Robbins to retrieve the birdie.

In [26]:
vect = TfidfVectorizer()
vect.fit_transform(reviews)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1731403 stored elements and shape (12500, 55739)>

In [29]:
X = vect.fit_transform(reviews)
Y = pd.DataFrame(X.toarray(), columns=vect.get_feature_names_out())
len(Y)

12500

In [30]:
Y.shape

(12500, 55739)

In [31]:
vect1 = TfidfVectorizer(stop_words="english")
X1 = vect1.fit_transform(reviews)
Y1 = pd.DataFrame(X.toarray(), columns=vect.get_feature_names_out())
Y1[:3]

,00,000,000s,003830,006,007,0079,0080,0083,0093638,...,élan,émigré,émigrés,était,état,étc,êxtase,ís,østbye,über
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
Y1.shape

(12500, 55739)

/Users/ankster/.virtualenvs/ML_AI/lib/python3.12/site-packages/sklearn/decomposition/_nmf.py:1728: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

,Word 1,Word 2,Word 3,Word 4,Word 5,Word 6,Word 7,Word 8,Word 9,Word 10
Topic 1,bovasso,10,linkage,specials,emptiveness,sibblings,pitt,wracking,specialness,joyed
Topic 2,morsel,mortenson,waffles,realism,sanitorium,10,deewani,enemy,wagnerian,magazine
Topic 3,fictionalizations,fierce,changruputra,dinah,satnitefever,churlish,pitt,female,winged,arrived
Topic 4,selena,entrepreneur,entrepreneurial,scottsboro,trousers,changruputra,trafficked,scouring,shimizu,tasking
Topic 5,mais,rivalling,chandni,pedophile,pinpoint,jest,pinku,docile,satisfying,activists
Topic 6,godby,acting,stepin,prediction,backlashes,actelone,rascism,pitt,satnitefever,nellie
Topic 7,voluptuousness,wins,diy,pbs,amc,higuchi,sneak,meditation,hill,wilkinson
Topic 8,ft,colourful,lanoir,hessman,eaters,frontyard,jezebel,hoydenish,frying,muckerji
Topic 9,lezlie,rascism,teruyo,joyed,dolby,pbs,kirge,santons,diamond,waffles
Topic 10,mujar,dish,worthing,occupational,kenji,thorazine,sanitorium,snug,angry,mujhe
Topic 11,letup,stepin,looker,faints,rapt,changruputra,pbs,beastmaster,treatise,lineker
Topic 12,bondless,iturbi,vampiress,raphaelite,externalization,nominators,ringer,daffily,tagged,embeciles
Topic 13,honored,hornblower,crazies,saterday,goldust,fierce,bubba,hag,fallacy,edging
Topic 14,grandiosely,actelone,rascism,activity,carwash,jeremey,willem,joyed,looks,mujar
Topic 15,scrounges,user,bernhard,mortenson,thorazine,10,fierce,thorssen,harrumphing,santons

array([[0.00021353, 0.04056014, 0.        , 0.        , 0.00783266],
       [0.        , 0.01937739, 0.00495799, 0.00420815, 0.01497865],
       [0.        , 0.00335063, 0.02050924, 0.        , 0.00925259]])

In [55]:
N_TOPICS = 5
nmf = NMF(n_components=N_TOPICS)
W = nmf.fit_transform(X1)  # Document-topic matrix
H = nmf.components_  # Topic-term matrix

In [62]:
N_TOPICS = 15
nmf = NMF(n_components=N_TOPICS)
W = nmf.fit_transform(X1)  # Document-topic matrix
H = nmf.components_  # Topic-term matrix

/Users/ankster/.virtualenvs/ML_AI/lib/python3.12/site-packages/sklearn/decomposition/_nmf.py:1728: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

In [63]:
words = np.array(vect.get_feature_names_out())
topic_words = pd.DataFrame(
    np.zeros((N_TOPICS, 10)),
    index=[f"Topic {i + 1}" for i in range(N_TOPICS)],
    columns=[f"Word {i + 1}" for i in range(10)],
).astype(str)
for i in range(N_TOPICS):
    ix = H[i].argsort()[::-1][:10]
    topic_words.iloc[i] = words[ix]

topic_words

,Word 1,Word 2,Word 3,Word 4,Word 5,Word 6,Word 7,Word 8,Word 9,Word 10
Topic 1,bovasso,10,linkage,specials,emptiveness,wracking,sibblings,satisfying,joyed,specialness
Topic 2,morsel,mortenson,waffles,realism,10,sanitorium,actelone,activity,deewani,enemy
Topic 3,fictionalizations,fierce,dinah,churlish,female,satnitefever,arrived,pitt,winged,changruputra
Topic 4,selena,entrepreneur,entrepreneurial,scottsboro,trousers,changruputra,trafficked,scouring,shimizu,tasking
Topic 5,letup,faints,farm,wroth,rapt,snowed,occupational,mopey,chewy,mais
Topic 6,godby,prediction,backlashes,rascism,actelone,acting,jeremey,lha,nellie,pitt
Topic 7,voluptuousness,wins,diy,pbs,amc,higuchi,sneak,meditation,hill,housed
Topic 8,rivalling,mais,pedophile,chandni,bernhard,carwash,jest,activists,pinpoint,pinku
Topic 9,stepin,changruputra,acting,angry,dish,treatise,beastmaster,walking,instincts,liev
Topic 10,scrounges,user,thorazine,worthing,sanitorium,duo,vampiress,bernhard,bondless,trousers
Topic 11,looker,kasi,mujar,dales,dallenbach,mujhe,snug,sick,snuck,beastmaster
Topic 12,ft,colourful,lanoir,hessman,frontyard,eaters,jezebel,hoydenish,frying,muckerji
Topic 13,honored,hornblower,crazies,fierce,saterday,goldust,bubba,hag,fallacy,edging
Topic 14,grandiosely,actelone,rascism,activity,jeremey,carwash,mujar,looks,joyed,frontyard
Topic 15,lezlie,teruyo,rascism,joyed,dolby,pbs,kirge,santons,diamond,lomax

In [64]:
words = np.array(vect.get_feature_names_out())
topic_words = pd.DataFrame(
    np.zeros((N_TOPICS, 10)),
    index=[f"Topic {i + 1}" for i in range(N_TOPICS)],
    columns=[f"Word {i + 1}" for i in range(10)],
).astype(str)
for i in range(N_TOPICS):
    ix = H[i].argsort()[::-1][:10]
    topic_words.iloc[i] = words[ix]

topic_words

,Word 1,Word 2,Word 3,Word 4,Word 5,Word 6,Word 7,Word 8,Word 9,Word 10
Topic 1,bovasso,10,linkage,specials,emptiveness,wracking,sibblings,satisfying,joyed,specialness
Topic 2,morsel,mortenson,waffles,realism,10,sanitorium,actelone,activity,deewani,enemy
Topic 3,fictionalizations,fierce,dinah,churlish,female,satnitefever,arrived,pitt,winged,changruputra
Topic 4,selena,entrepreneur,entrepreneurial,scottsboro,trousers,changruputra,trafficked,scouring,shimizu,tasking
Topic 5,letup,faints,farm,wroth,rapt,snowed,occupational,mopey,chewy,mais
Topic 6,godby,prediction,backlashes,rascism,actelone,acting,jeremey,lha,nellie,pitt
Topic 7,voluptuousness,wins,diy,pbs,amc,higuchi,sneak,meditation,hill,housed
Topic 8,rivalling,mais,pedophile,chandni,bernhard,carwash,jest,activists,pinpoint,pinku
Topic 9,stepin,changruputra,acting,angry,dish,treatise,beastmaster,walking,instincts,liev
Topic 10,scrounges,user,thorazine,worthing,sanitorium,duo,vampiress,bernhard,bondless,trousers
Topic 11,looker,kasi,mujar,dales,dallenbach,mujhe,snug,sick,snuck,beastmaster
Topic 12,ft,colourful,lanoir,hessman,frontyard,eaters,jezebel,hoydenish,frying,muckerji
Topic 13,honored,hornblower,crazies,fierce,saterday,goldust,bubba,hag,fallacy,edging
Topic 14,grandiosely,actelone,rascism,activity,jeremey,carwash,mujar,looks,joyed,frontyard
Topic 15,lezlie,teruyo,rascism,joyed,dolby,pbs,kirge,santons,diamond,lomax

In [66]:
topic_mapping = {
    "Topic 3": "Fiction",
    "Topic 7": "War",
    "Topic 8": "Comedy",
    "Topic 12": "Book Adaptation",
    "Topic 13": "Horror",
    "Topic 15": "Martial Arts / Action",
}

In [67]:
W = pd.DataFrame(W, columns=[f"Topic {i + 1}" for i in range(N_TOPICS)])
W["max_topic"] = W.apply(lambda x: topic_mapping.get(x.idxmax()), axis=1)
W[pd.notnull(W["max_topic"])].head(10)

,Topic 1,Topic 2,Topic 3,Topic 4,Topic 5,Topic 6,Topic 7,Topic 8,Topic 9,Topic 10,Topic 11,Topic 12,Topic 13,Topic 14,Topic 15,max_topic
1,0.000000,0.015256,0.000000,0.002759,0.000000,0.002927,0.000000,0.009983,0.000000,0.000000,0.003266,0.001591,0.046417,0.015854,0.000599,Horror
2,0.000000,0.001032,0.018872,0.000000,0.001137,0.000000,0.000000,0.006821,0.000580,0.003775,0.014513,0.007558,0.000000,0.006784,0.003458,Fiction
8,0.020177,0.000000,0.011342,0.002092,0.016265,0.005835,0.010751,0.022496,0.012283,0.000000,0.000000,0.000939,0.000687,0.000000,0.005595,Comedy
10,0.000000,0.017313,0.038966,0.000000,0.000000,0.000000,0.000000,0.010961,0.002131,0.000000,0.003958,0.022819,0.000000,0.000000,0.009886,Fiction
11,0.006482,0.015181,0.006576,0.000061,0.005410,0.000000,0.009135,0.026752,0.002018,0.000000,0.003532,0.003074,0.012535,0.000000,0.000000,Comedy
13,0.038220,0.000000,0.065238,0.000000,0.022630,0.000000,0.012326,0.014656,0.023787,0.019090,0.002686,0.000000,0.004714,0.023972,0.016340,Fiction
16,0.000000,0.001619,0.080476,0.000829,0.007467,0.007237,0.000000,0.021390,0.000000,0.005145,0.000000,0.000000,0.000000,0.034697,0.003057,Fiction
17,0.011967,0.000000,0.000934,0.014317,0.004290,0.000326,0.004600,0.009370,0.000000,0.000000,0.006754,0.045392,0.003568,0.011425,0.000000,Book Adaptation
19,0.016132,0.012681,0.029315,0.000357,0.013035,0.027637,0.003994,0.000000,0.004705,0.000000,0.005892,0.014747,0.000000,0.000000,0.027946,Fiction
24,0.017169,0.012853,0.000983,0.000428,0.009786,0.002999,0.020388,0.010694,0.004608,0.000000,0.012830,0.001656,0.000000,0.008863,0.000753,War