In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("train.csv")

In [5]:
X_test = pd.read_csv("test.csv")

date_id                                 0
S10                                     0
S1                                      0
P9                                      0
P8                                      0
                                       ..
E8                                      0
E7                                      0
E6                                      0
E4                                      0
lagged_market_forward_excess_returns    0
Length: 99, dtype: int64

In [7]:
X_test.isna().sum().sum()

np.int64(0)

In [8]:
df.isna().sum()

date_id                             0
D1                                  0
D2                                  0
D3                                  0
D4                                  0
                                 ...
V8                               1006
V9                               4539
forward_returns                     0
risk_free_rate                      0
market_forward_excess_returns       0
Length: 98, dtype: int64

In [9]:
df.describe()

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
count,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,9021.000000,...,8015.000000,8015.000000,7509.000000,8015.000000,7510.000000,8015.000000,4482.000000,9021.000000,9021.000000,9021.000000
mean,4510.000000,0.031593,0.031593,0.047777,0.573994,0.190445,-0.238111,0.045671,0.142667,0.143000,...,0.489076,0.506589,0.373584,0.288874,0.145886,0.303203,0.125155,0.000471,0.000107,0.000053
std,2604.282723,0.174923,0.174923,0.213307,0.494522,0.392674,0.425951,0.208783,0.349752,0.350092,...,0.306060,0.306216,1.151136,0.312905,1.324779,0.350627,1.273912,0.010541,0.000088,0.010558
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000661,0.000661,-2.723527,0.000661,-2.027551,0.000661,-1.497420,-0.039754,-0.000004,-0.040582
25%,2255.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.206680,0.236772,-0.470083,0.000661,-0.795846,0.000661,-0.734003,-0.004319,0.000008,-0.004747
50%,4510.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.491402,0.517857,0.280020,0.182540,-0.100889,0.101852,-0.175851,0.000659,0.000097,0.000255
75%,6765.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.759921,0.771164,1.119295,0.519841,0.791181,0.588790,0.678213,0.005896,0.000193,0.005479
max,9020.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,6.809912,1.000000,12.678264,1.000000,12.997536,0.040661,0.000317,0.040551

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9021 entries, 0 to 9020
Data columns (total 98 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date_id                        9021 non-null   int64
 1   D1                             9021 non-null   int64
 2   D2                             9021 non-null   int64
 3   D3                             9021 non-null   int64
 4   D4                             9021 non-null   int64
 5   D5                             9021 non-null   int64
 6   D6                             9021 non-null   int64
 7   D7                             9021 non-null   int64
 8   D8                             9021 non-null   int64
 9   D9                             9021 non-null   int64
 10  E1                             7237 non-null   float64
 11  E10                            8015 non-null   float64
 12  E11                            8015 non-null   float64
 13  E12                            8015 non-null   float64
 14  E13                            8015 non-null   float64
 15  E14                            8015 non-null   float64
 16  E15                            8015 non-null   float64
 17  E16                            8015 non-null   float64
 18  E17                            8015 non-null   float64
 19  E18                            8015 non-null   float64
 20  E19                            8015 non-null   float64
 21  E2                             8015 non-null   float64
 22  E20                            7405 non-null   float64
 23  E3                             8015 non-null   float64
 24  E4                             8015 non-null   float64
 25  E5                             8015 non-null   float64
 26  E6                             8015 non-null   float64
 27  E7                             2052 non-null   float64
 28  E8                             8015 non-null   float64
 29  E9                             8015 non-null   float64
 30  I1                             8015 non-null   float64
 31  I2                             8015 non-null   float64
 32  I3                             8015 non-null   float64
 33  I4                             8015 non-null   float64
 34  I5                             8015 non-null   float64
 35  I6                             8015 non-null   float64
 36  I7                             8015 non-null   float64
 37  I8                             8015 non-null   float64
 38  I9                             8015 non-null   float64
 39  M1                             3474 non-null   float64
 40  M10                            8015 non-null   float64
 41  M11                            8015 non-null   float64
 42  M12                            8015 non-null   float64
 43  M13                            3481 non-null   float64
 44  M14                            3481 non-null   float64
 45  M15                            8015 non-null   float64
 46  M16                            8015 non-null   float64
 47  M17                            8015 non-null   float64
 48  M18                            8015 non-null   float64
 49  M2                             5804 non-null   float64
 50  M3                             7003 non-null   float64
 51  M4                             8015 non-null   float64
 52  M5                             5738 non-null   float64
 53  M6                             3978 non-null   float64
 54  M7                             8015 non-null   float64
 55  M8                             8015 non-null   float64
 56  M9                             8015 non-null   float64
 57  P1                             8015 non-null   float64
 58  P10                            8015 non-null   float64
 59  P11                            8015 non-null   float64
 60  P12                            8015 non-null   float64
 61  P13                            8015 non-null   float64
 62  P2                             8015 non-null   float64
 63  P3                             8015 non-null   float64
 64  P4                             8015 non-null   float64
 65  P5                             7447 non-null   float64
 66  P6                             7383 non-null   float64
 67  P7                             7405 non-null   float64
 68  P8                             8015 non-null   float64
 69  P9                             8015 non-null   float64
 70  S1                             8015 non-null   float64
 71  S10                            8015 non-null   float64
 72  S11                            8015 non-null   float64
 73  S12                            5484 non-null   float64
 74  S2                             8015 non-null   float64
 75  S3                             3288 non-null   float64
 76  S4                             8015 non-null   float64
 77  S5                             7510 non-null   float64
 78  S6                             8015 non-null   float64
 79  S7                             8015 non-null   float64
 80  S8                             6012 non-null   float64
 81  S9                             8015 non-null   float64
 82  V1                             8015 non-null   float64
 83  V10                            2972 non-null   float64
 84  V11                            8015 non-null   float64
 85  V12                            8015 non-null   float64
 86  V13                            7510 non-null   float64
 87  V2                             8015 non-null   float64
 88  V3                             8015 non-null   float64
 89  V4                             8015 non-null   float64
 90  V5                             7509 non-null   float64
 91  V6                             8015 non-null   float64
 92  V7                             7510 non-null   float64
 93  V8                             8015 non-null   float64
 94  V9                             4482 non-null   float64
 95  forward_returns                9021 non-null   float64
 96  risk_free_rate                 9021 non-null   float64
 97  market_forward_excess_returns  9021 non-null   float64
dtypes: float64(88), int64(10)
memory usage: 6.7 MB

In [11]:
df

,date_id,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,V3,V4,V5,V6,V7,V8,V9,forward_returns,risk_free_rate,market_forward_excess_returns
0,0,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.002421,0.000301,-0.003038
1,1,0,0,0,1,1,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.008495,0.000303,-0.009114
2,2,0,0,0,1,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.009624,0.000301,-0.010243
3,3,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004662,0.000299,0.004046
4,4,0,0,0,1,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.011686,0.000299,-0.012301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9016,9016,0,0,0,1,0,0,0,0,0,...,0.208995,0.484788,0.717308,0.677249,-0.327455,0.083995,-0.380452,-0.000015,0.000151,-0.000477
9017,9017,0,0,0,1,0,0,0,0,0,...,0.082011,0.482804,1.001028,0.596561,-0.372979,0.094246,-0.427355,-0.005199,0.000150,-0.005661
9018,9018,0,0,0,1,0,-1,0,0,0,...,0.334656,0.486772,0.894502,0.656746,-0.282024,0.090608,-0.381337,0.005930,0.000150,0.005467
9019,9019,0,0,0,1,0,-1,0,0,0,...,0.163360,0.492725,1.117639,0.674603,-0.445261,0.106481,-0.477635,0.008173,0.000150,0.007710
9020,9020,0,0,0,1,0,-1,0,0,0,...,0.177910,0.501323,1.231340,0.486111,-0.562036,0.089947,-0.543367,0.009524,0.000149,0.009062

In [12]:
columns = df.columns
df.info()
print(columns)


def fill(x):
    df[x] = df[x].map(lambda x: -999.0 if np.isnan(x) else x)
    print(df[x].isnull().sum())
    return df[x]


for x in columns:
    df[x] = df[x].astype("float64")
    df[x] = fill(x)
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9021 entries, 0 to 9020
Data columns (total 98 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date_id                        9021 non-null   int64
 1   D1                             9021 non-null   int64
 2   D2                             9021 non-null   int64
 3   D3                             9021 non-null   int64
 4   D4                             9021 non-null   int64
 5   D5                             9021 non-null   int64
 6   D6                             9021 non-null   int64
 7   D7                             9021 non-null   int64
 8   D8                             9021 non-null   int64
 9   D9                             9021 non-null   int64
 10  E1                             7237 non-null   float64
 11  E10                            8015 non-null   float64
 12  E11                            8015 non-null   float64
 13  E12                            8015 non-null   float64
 14  E13                            8015 non-null   float64
 15  E14                            8015 non-null   float64
 16  E15                            8015 non-null   float64
 17  E16                            8015 non-null   float64
 18  E17                            8015 non-null   float64
 19  E18                            8015 non-null   float64
 20  E19                            8015 non-null   float64
 21  E2                             8015 non-null   float64
 22  E20                            7405 non-null   float64
 23  E3                             8015 non-null   float64
 24  E4                             8015 non-null   float64
 25  E5                             8015 non-null   float64
 26  E6                             8015 non-null   float64
 27  E7                             2052 non-null   float64
 28  E8                             8015 non-null   float64
 29  E9                             8015 non-null   float64
 30  I1                             8015 non-null   float64
 31  I2                             8015 non-null   float64
 32  I3                             8015 non-null   float64
 33  I4                             8015 non-null   float64
 34  I5                             8015 non-null   float64
 35  I6                             8015 non-null   float64
 36  I7                             8015 non-null   float64
 37  I8                             8015 non-null   float64
 38  I9                             8015 non-null   float64
 39  M1                             3474 non-null   float64
 40  M10                            8015 non-null   float64
 41  M11                            8015 non-null   float64
 42  M12                            8015 non-null   float64
 43  M13                            3481 non-null   float64
 44  M14                            3481 non-null   float64
 45  M15                            8015 non-null   float64
 46  M16                            8015 non-null   float64
 47  M17                            8015 non-null   float64
 48  M18                            8015 non-null   float64
 49  M2                             5804 non-null   float64
 50  M3                             7003 non-null   float64
 51  M4                             8015 non-null   float64
 52  M5                             5738 non-null   float64
 53  M6                             3978 non-null   float64
 54  M7                             8015 non-null   float64
 55  M8                             8015 non-null   float64
 56  M9                             8015 non-null   float64
 57  P1                             8015 non-null   float64
 58  P10                            8015 non-null   float64
 59  P11                            8015 non-null   float64
 60  P12                            8015 non-null   float64
 61  P13                            8015 non-null   float64
 62  P2                             8015 non-null   float64
 63  P3                             8015 non-null   float64
 64  P4                             8015 non-null   float64
 65  P5                             7447 non-null   float64
 66  P6                             7383 non-null   float64
 67  P7                             7405 non-null   float64
 68  P8                             8015 non-null   float64
 69  P9                             8015 non-null   float64
 70  S1                             8015 non-null   float64
 71  S10                            8015 non-null   float64
 72  S11                            8015 non-null   float64
 73  S12                            5484 non-null   float64
 74  S2                             8015 non-null   float64
 75  S3                             3288 non-null   float64
 76  S4                             8015 non-null   float64
 77  S5                             7510 non-null   float64
 78  S6                             8015 non-null   float64
 79  S7                             8015 non-null   float64
 80  S8                             6012 non-null   float64
 81  S9                             8015 non-null   float64
 82  V1                             8015 non-null   float64
 83  V10                            2972 non-null   float64
 84  V11                            8015 non-null   float64
 85  V12                            8015 non-null   float64
 86  V13                            7510 non-null   float64
 87  V2                             8015 non-null   float64
 88  V3                             8015 non-null   float64
 89  V4                             8015 non-null   float64
 90  V5                             7509 non-null   float64
 91  V6                             8015 non-null   float64
 92  V7                             7510 non-null   float64
 93  V8                             8015 non-null   float64
 94  V9                             4482 non-null   float64
 95  forward_returns                9021 non-null   float64
 96  risk_free_rate                 9021 non-null   float64
 97  market_forward_excess_returns  9021 non-null   float64
dtypes: float64(88), int64(10)
memory usage: 6.7 MB
Index(['date_id', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'E1',
       'E10', 'E11', 'E12', 'E13', 'E14', 'E15', 'E16', 'E17', 'E18', 'E19',
       'E2', 'E20', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'I1', 'I2', 'I3',
       'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'M1', 'M10', 'M11', 'M12', 'M13',
       'M14', 'M15', 'M16', 'M17', 'M18', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7',
       'M8', 'M9', 'P1', 'P10', 'P11', 'P12', 'P13', 'P2', 'P3', 'P4', 'P5',
       'P6', 'P7', 'P8', 'P9', 'S1', 'S10', 'S11', 'S12', 'S2', 'S3', 'S4',
       'S5', 'S6', 'S7', 'S8', 'S9', 'V1', 'V10', 'V11', 'V12', 'V13', 'V2',
       'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'forward_returns',
       'risk_free_rate', 'market_forward_excess_returns'],
      dtype='object')
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

date_id                          0
D1                               0
D2                               0
D3                               0
D4                               0
                                ..
V8                               0
V9                               0
forward_returns                  0
risk_free_rate                   0
market_forward_excess_returns    0
Length: 98, dtype: int64

In [13]:
X_train = df.iloc[0:8841].copy()
X_val = df.iloc[8841:9021].copy()

In [14]:
import sklearn

In [15]:
from sklearn.ensemble import RandomForestRegressor

In [16]:
y_train = X_train.pop("forward_returns")
y_val = X_val.pop("forward_returns")
cols_to_drop = [
    "forward_returns",
]
X_train = X_train.drop(columns=cols_to_drop, errors="ignore")
X_val = X_val.drop(columns=cols_to_drop, errors="ignore")

# Also ensure X_test has the same columns dropped
X_test = X_test.drop(columns=cols_to_drop, errors="ignore")

In [17]:
rf = RandomForestRegressor(random_state=42, n_jobs=-1)

In [18]:
rf.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [19]:
y_val_pred = rf.predict(X_val)

In [20]:
from sklearn.metrics import r2_score

r2_score(y_val, y_val_pred)

0.9986143108842195

In [22]:
import os
import pandas as pd
import numpy as np
import polars as pl
import kaggle_evaluation.default_inference_server
import traceback

# --- CONFIGURATIONS ---
# NO SIGNAL LOGIC applied here.
# We are sending the raw model output to establish a baseline and ensure technical success.

# 1. Capture the exact training columns
# Ensure X_train is defined in memory before running this cell
train_cols = X_train.columns.tolist()


def predict(test: pl.DataFrame) -> float:
    """
    Test 1: Raw RF Prediction returned as FLOAT.
    This satisfies the Hull Competition API requirement for a single float return per row.
    """
    try:
        # 1. CONVERT Polars -> Pandas (Single Row)
        test_pd = test.to_pandas()

        # 2. FEATURE ALIGNMENT
        # Rename lagged columns to match training features
        rename_map = {
            "lagged_risk_free_rate": "risk_free_rate",
            "lagged_market_forward_excess_returns": "market_forward_excess_returns",
        }
        test_pd = test_pd.rename(columns=rename_map)

        # Drop forbidden columns if they exist
        drop_cols_test = ["is_scored", "lagged_forward_returns"]
        existing_cols_to_drop = [c for c in drop_cols_test if c in test_pd.columns]
        test_pd = test_pd.drop(columns=existing_cols_to_drop)

        # Reindex to match training data exactly (fills missing with -999.0)
        test_pd = test_pd.reindex(columns=train_cols, fill_value=-999.0)
        test_pd = test_pd.fillna(-999.0)

        # 3. PREDICT RAW RETURNS
        # Access [0] because the server sends 1 row and expects 1 scalar return.
        raw_pred = float(rf.predict(test_pd)[0])

        # 4. RETURN RAW FLOAT
        # Returning the raw prediction avoids clipping issues and lets us see the model's true behavior.
        return raw_pred

    except Exception as e:
        # SAFETY NET: Return 0.0 (neutral) if anything crashes
        print(f"CRASH IN PREDICT: {e}")
        traceback.print_exc()
        return 0.0


# Initialize Server
inference_server = kaggle_evaluation.default_inference_server.DefaultInferenceServer(
    predict
)

if os.getenv("KAGGLE_IS_COMPETITION_RERUN"):
    # REAL SUBMISSION
    inference_server.serve()
else:
    # LOCAL TEST
    print("Running local test...")
    try:
        inference_server.run_local_gateway(("hull-tactical-market-prediction/",))
        print("Local gateway finished successfully.")
    except Exception as e:
        print(f"Local gateway reported error (safe to ignore if file is created): {e}")

    # FORCE CREATE DUMMY FILE
    print("Creating dummy submission file...")
    dummy = pd.DataFrame({"prediction": [0.0] * 5})
    dummy.to_parquet("submission.parquet")
    print("submission.parquet created successfully.")

ModuleNotFoundError: No module named 'kaggle_evaluation'