In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.pyplot import xticks, yticks
import seaborn as sns
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [3]:
digits.data.shape

(1797, 64)

In [4]:
df = pd.read_clipboard()

In [5]:
df

Empty DataFrame
Columns: [PCA_instructor]
Index: []

In [6]:
df.iloc[1:]

Empty DataFrame
Columns: [PCA_instructor]
Index: []

In [7]:
df.loc[1:]

Empty DataFrame
Columns: [PCA_instructor]
Index: []

NameError: name 'vector' is not defined

Empty DataFrame
Columns: []
Index: []

Index([], dtype='object')

Empty DataFrame
Columns: []
Index: []

In [10]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
x

array([[1, 2],
       [3, 4]])

In [11]:
y

array([[1, 2],
       [1, 2]])

In [12]:
x * y

array([[1, 4],
       [3, 8]])

In [13]:
np.dot(x, y)

array([[ 3,  6],
       [ 7, 14]])

In [14]:
x @ y

array([[ 3,  6],
       [ 7, 14]])

In [15]:
x = np.array([[2, 1, 1], [3, 2, 1], [2, 1, 2]])
np.linalg.inv(x)

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])

In [16]:
35 * 0.25 * 20

175.0

In [17]:
120 * 0.25

30.0

In [18]:
(120 / 4)

30.0

In [19]:
120 / 4 + 120 * 1

150.0

In [20]:
2.205 * 0.0328

0.07232400000000001

In [23]:
v1 = np.array([[4], [9]])
b1 = np.eye(2)
b2 = np.array(np.array([[1, 1], [2, 3]]))
M = np.linalg.inv(b2)
M
v2 = M @ v1
v2

array([[3.],
       [1.]])

In [24]:
M @ v1

array([[3.],
       [1.]])

In [25]:
# exercise
v1 = np.array([[8], [6]])
b2 = np.array([[2, -2], [1, 1]])
M = np.linalg.inv(b2)
v2 = M @ v1
v2

array([[5.],
       [1.]])

In [26]:
M

array([[ 0.25,  0.5 ],
       [-0.25,  0.5 ]])

In [27]:
b2

array([[ 2, -2],
       [ 1,  1]])

In [29]:
# exercise2
b1 = np.eye(2)
b2 = np.array([[1, 1], [-2, 1]])
M = np.linalg.inv(b2)

In [30]:
v1 = np.array([[25], [28]])
v2 = M @ v1
v2

array([[-1.],
       [26.]])

In [32]:
v1 = np.array([[-3], [12]])
M = b2
v2 = M @ v1
v2

array([[ 9],
       [18]])

## Dimensionality Reduction

In [37]:
df = pd.read_clipboard()

In [38]:
df

  Point  X    Y
0    P1  2  1.0
1    P2  3  1.5
2    P3  4  2.0
3    P4  6  3.0
4    P5  7  3.5
5    P6  8  4.0

In [39]:
df["X"] / df["Y"]

0    2.0
1    2.0
2    2.0
3    2.0
4    2.0
5    2.0
dtype: float64

In [41]:
df["X"].corr(df["Y"])

np.float64(1.0)

In [43]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)
X = df[["X", "Y"]]
pca.fit(X)

PCA(n_components=1)

In [44]:
pca.components_

array([[0.89442719, 0.4472136 ]])

In [45]:
pca.explained_variance_

array([7.])

In [46]:
pca.explained_variance_ratio_

array([1.])

In [3]:
import numpy as np

M = np.array([[1, 2], [1, 1]])
v1 = np.array([[1], [1]])
v2 = M @ v1
v2

array([[3],
       [2]])