In [1]:
import re

In [27]:
word = "Hello I am Deven aged 24, brother is 30"
pattern = "\d+"
result = re.findall(pattern, word)
print(*result)

24 30

In [3]:
WORD_RE = re.compile(r"\w+")

In [25]:
re.findall(WORD_RE, word)

['Hello', 'I', 'am', 'Deven', 'aged', '24']

In [6]:
import pandas as pd

In [53]:
s = pd.Series(["a1a2 d4eve5n", "b1", "c2"], index=["A", "B", "C"])

In [21]:
s.str.extractall(r"[a-e](\d)+")

         0
  match
A 0      1
  1      2
  2      4
  3      5

In [22]:
WORD_RE.findall(word)

['Hello', 'I', 'am', 'Deven', 'aged', '24']

In [24]:
x = WORD_RE.finditer(word)

for l in x:
    w = l.group()
    print(w)

Hello
I
am
Deven
aged
24

In [49]:
only_words = re.compile(r"[a-zA-Z]+")

In [50]:
only_words.findall(word)

['Hello', 'I', 'am', 'Deven', 'aged', 'brother', 'is']

In [57]:
s.str.extractall(r"[a-e](\d)")

         0
  match
A 0      1
  1      2
  2      4
  3      5
B 0      1
C 0      2