## Multinomial and Bernoulli Naive Bayes

For understanding Multinomial and Bernoulli Naive Bayes, we will start with a small example and understand the end to end process. In another notebook, we will build a full-fledged email spam classifier.

To start with, let's take a few sentences and classify them in two different classes - *education* or *cinema*. Each sentence will represent one document. In real-world cases, a document be any piece of text such as an email, a news article, a book review, a tweet etc.
The analysis and the algorithm involved doesn’t depend on the type of document we use.

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
df = pd.read_csv("example_train.csv")

In [3]:
df

                                            Document      Class
0         Upgrad is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

In [4]:
df["Class_mapped"] = df["Class"].map({"cinema": 0, "education": 1})

In [5]:
df

                                            Document      Class  Class_mapped
0         Upgrad is a great educational institution.  education             1
1            Educational greatness depends on ethics  education             1
2  A story of great ethics and educational greatness  education             1
3                           Sholey is a great cinema     cinema             0
4                   good movie depends on good story     cinema             0

In [6]:
df.drop("Class", axis=1, inplace=True)

In [7]:
# Converting data frame into numpy array
train = df.values
X_train = train[:, 0]
y_train = train[:, 1]

In [8]:
y_train.dtype

dtype('O')

In [9]:
# Converting into integer type
y_train = y_train.astype("int")

In [10]:
X_train, y_train

(array(['Upgrad is a great educational institution.',
        'Educational greatness depends on ethics',
        'A story of great ethics and educational greatness',
        'Sholey is a great cinema', 'good movie depends on good story'],
       dtype=object),
 array([1, 1, 1, 0, 0]))

In [11]:
y_train.dtype

dtype('int64')

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

help(CountVectorizer)

Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |
 |  Convert a collection of text documents to a matrix of token counts.
 |
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |
 |  For an efficiency comparison of the different feature extractors, see
 |  :ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.
 |
 |  Read more in the :ref:`User Guide <text_feature_extraction>`.
 |
 |  Parameters
 |  ----------
 |  input : {'filename', 'file', 'content'}, default='content'
 |      - If `'filename'`, the sequence passed as an argument to fit is
 |        expected to be a list of filenames that need reading to fetch
 |        the raw content to analyze.
 |
 |      - If `'file'`, the sequence items must have a 'read' method (file-like
 |        object) that is called to fetch the bytes in memory.
 |
 |      - If `'content'`, the input is expected to be a sequence of items that
 |        can be of type string or byte.
 |
 |  encoding : str, default='utf-8'
 |      If bytes or files are given to analyze, this encoding is used to
 |      decode.
 |
 |  decode_error : {'strict', 'ignore', 'replace'}, default='strict'
 |      Instruction on what to do if a byte sequence is given to analyze that
 |      contains characters not of the given `encoding`. By default, it is
 |      'strict', meaning that a UnicodeDecodeError will be raised. Other
 |      values are 'ignore' and 'replace'.
 |
 |  strip_accents : {'ascii', 'unicode'} or callable, default=None
 |      Remove accents and perform other character normalization
 |      during the preprocessing step.
 |      'ascii' is a fast method that only works on characters that have
 |      a direct ASCII mapping.
 |      'unicode' is a slightly slower method that works on any characters.
 |      None (default) means no character normalization is performed.
 |
 |      Both 'ascii' and 'unicode' use NFKD normalization from
 |      :func:`unicodedata.normalize`.
 |
 |  lowercase : bool, default=True
 |      Convert all characters to lowercase before tokenizing.
 |
 |  preprocessor : callable, default=None
 |      Override the preprocessing (strip_accents and lowercase) stage while
 |      preserving the tokenizing and n-grams generation steps.
 |      Only applies if ``analyzer`` is not callable.
 |
 |  tokenizer : callable, default=None
 |      Override the string tokenization step while preserving the
 |      preprocessing and n-grams generation steps.
 |      Only applies if ``analyzer == 'word'``.
 |
 |  stop_words : {'english'}, list, default=None
 |      If 'english', a built-in stop word list for English is used.
 |      There are several known issues with 'english' and you should
 |      consider an alternative (see :ref:`stop_words`).
 |
 |      If a list, that list is assumed to contain stop words, all of which
 |      will be removed from the resulting tokens.
 |      Only applies if ``analyzer == 'word'``.
 |
 |      If None, no stop words will be used. In this case, setting `max_df`
 |      to a higher value, such as in the range (0.7, 1.0), can automatically detect
 |      and filter stop words based on intra corpus document frequency of terms.
 |
 |  token_pattern : str or None, default=r"(?u)\\b\\w\\w+\\b"
 |      Regular expression denoting what constitutes a "token", only used
 |      if ``analyzer == 'word'``. The default regexp select tokens of 2
 |      or more alphanumeric characters (punctuation is completely ignored
 |      and always treated as a token separator).
 |
 |      If there is a capturing group in token_pattern then the
 |      captured group content, not the entire match, becomes the token.
 |      At most one capturing group is permitted.
 |
 |  ngram_range : tuple (min_n, max_n), default=(1, 1)
 |      The lower and upper boundary of the range of n-values for different
 |      word n-grams or char n-grams to be extracted. All values of n such
 |      such that min_n <= n <= max_n will be used. For example an
 |      ``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` means
 |      unigrams and bigrams, and ``(2, 2)`` means only bigrams.
 |      Only applies if ``analyzer`` is not callable.
 |
 |  analyzer : {'word', 'char', 'char_wb'} or callable, default='word'
 |      Whether the feature should be made of word n-gram or character
 |      n-grams.
 |      Option 'char_wb' creates character n-grams only from text inside
 |      word boundaries; n-grams at the edges of words are padded with space.
 |
 |      If a callable is passed it is used to extract the sequence of features
 |      out of the raw, unprocessed input.
 |
 |      .. versionchanged:: 0.21
 |
 |      Since v0.21, if ``input`` is ``filename`` or ``file``, the data is
 |      first read from the file and then passed to the given callable
 |      analyzer.
 |
 |  max_df : float in range [0.0, 1.0] or int, default=1.0
 |      When building the vocabulary ignore terms that have a document
 |      frequency strictly higher than the given threshold (corpus-specific
 |      stop words).
 |      If float, the parameter represents a proportion of documents, integer
 |      absolute counts.
 |      This parameter is ignored if vocabulary is not None.
 |
 |  min_df : float in range [0.0, 1.0] or int, default=1
 |      When building the vocabulary ignore terms that have a document
 |      frequency strictly lower than the given threshold. This value is also
 |      called cut-off in the literature.
 |      If float, the parameter represents a proportion of documents, integer
 |      absolute counts.
 |      This parameter is ignored if vocabulary is not None.
 |
 |  max_features : int, default=None
 |      If not None, build a vocabulary that only consider the top
 |      `max_features` ordered by term frequency across the corpus.
 |      Otherwise, all features are used.
 |
 |      This parameter is ignored if vocabulary is not None.
 |
 |  vocabulary : Mapping or iterable, default=None
 |      Either a Mapping (e.g., a dict) where keys are terms and values are
 |      indices in the feature matrix, or an iterable over terms. If not
 |      given, a vocabulary is determined from the input documents. Indices
 |      in the mapping should not be repeated and should not have any gap
 |      between 0 and the largest index.
 |
 |  binary : bool, default=False
 |      If True, all non zero counts are set to 1. This is useful for discrete
 |      probabilistic models that model binary events rather than integer
 |      counts.
 |
 |  dtype : dtype, default=np.int64
 |      Type of the matrix returned by fit_transform() or transform().
 |
 |  Attributes
 |  ----------
 |  vocabulary_ : dict
 |      A mapping of terms to feature indices.
 |
 |  fixed_vocabulary_ : bool
 |      True if a fixed vocabulary of term to indices mapping
 |      is provided by the user.
 |
 |  See Also
 |  --------
 |  HashingVectorizer : Convert a collection of text documents to a
 |      matrix of token counts.
 |
 |  TfidfVectorizer : Convert a collection of raw documents to a matrix
 |      of TF-IDF features.
 |
 |  Examples
 |  --------
 |  >>> from sklearn.feature_extraction.text import CountVectorizer
 |  >>> corpus = [
 |  ...     'This is the first document.',
 |  ...     'This document is the second document.',
 |  ...     'And this is the third one.',
 |  ...     'Is this the first document?',
 |  ... ]
 |  >>> vectorizer = CountVectorizer()
 |  >>> X = vectorizer.fit_transform(corpus)
 |  >>> vectorizer.get_feature_names_out()
 |  array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
 |         'this'], ...)
 |  >>> print(X.toarray())
 |  [[0 1 1 1 0 0 1 0 1]
 |   [0 2 0 1 0 1 1 0 1]
 |   [1 0 0 1 1 0 1 1 1]
 |   [0 1 1 1 0 0 1 0 1]]
 |  >>> vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
 |  >>> X2 = vectorizer2.fit_transform(corpus)
 |  >>> vectorizer2.get_feature_names_out()
 |  array(['and this', 'document is', 'first document', 'is the', 'is this',
 |         'second document', 'the first', 'the second', 'the third', 'third one',
 |         'this document', 'this is', 'this the'], ...)
 |   >>> print(X2.toarray())
 |   [[0 0 1 1 0 0 1 0 0 0 0 1 0]
 |   [0 1 0 1 0 1 0 1 0 0 1 0 0]
 |   [1 0 0 1 0 0 0 0 1 1 0 1 0]
 |   [0 0 1 0 1 0 1 0 0 0 0 0 1]]
 |
 |  Method resolution order:
 |      CountVectorizer
 |      _VectorizerMixin
 |      sklearn.base.BaseEstimator
 |      sklearn.utils._repr_html.base.ReprHTMLMixin
 |      sklearn.utils._repr_html.base._HTMLDocumentationLinkMixin
 |      sklearn.utils._metadata_requests._MetadataRequester
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __sklearn_tags__(self)
 |
 |  fit(self, raw_documents, y=None)
 |      Learn a vocabulary dictionary of all tokens in the raw documents.
 |
 |      Parameters
 |      ----------
 |      raw_documents : iterable
 |          An iterable which generates either str, unicode or file objects.
 |
 |      y : None
 |          This parameter is ignored.
 |
 |      Returns
 |      -------
 |      self : object
 |          Fitted vectorizer.
 |
 |  fit_transform(self, raw_documents, y=None)
 |      Learn the vocabulary dictionary and return document-term matrix.
 |
 |      This is equivalent to fit followed by transform, but more efficiently
 |      implemented.
 |
 |      Parameters
 |      ----------
 |      raw_documents : iterable
 |          An iterable which generates either str, unicode or file objects.
 |
 |      y : None
 |          This parameter is ignored.
 |
 |      Returns
 |      -------
 |      X : array of shape (n_samples, n_features)
 |          Document-term matrix.
 |
 |  get_feature_names_out(self, input_features=None)
 |      Get output feature names for transformation.
 |
 |      Parameters
 |      ----------
 |      input_features : array-like of str or None, default=None
 |          Not used, present here for API consistency by convention.
 |
 |      Returns
 |      -------
 |      feature_names_out : ndarray of str objects
 |          Transformed feature names.
 |
 |  inverse_transform(self, X)
 |      Return terms per document with nonzero entries in X.
 |
 |      Parameters
 |      ----------
 |      X : {array-like, sparse matrix} of shape (n_samples, n_features)
 |          Document-term matrix.
 |
 |      Returns
 |      -------
 |      X_original : list of arrays of shape (n_samples,)
 |          List of arrays of terms.
 |
 |  transform(self, raw_documents)
 |      Transform documents to document-term matrix.
 |
 |      Extract token counts out of raw text documents using the vocabulary
 |      fitted with fit or the one provided to the constructor.
 |
 |      Parameters
 |      ----------
 |      raw_documents : iterable
 |          An iterable which generates either str, unicode or file objects.
 |
 |      Returns
 |      -------
 |      X : sparse matrix of shape (n_samples, n_features)
 |          Document-term matrix.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {'_parameter_constraints': <class 'dict'>}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from _VectorizerMixin:
 |
 |  build_analyzer(self)
 |      Return a callable to process input data.
 |
 |      The callable handles preprocessing, tokenization, and n-grams generation.
 |
 |      Returns
 |      -------
 |      analyzer: callable
 |          A function to handle preprocessing, tokenization
 |          and n-grams generation.
 |
 |  build_preprocessor(self)
 |      Return a function to preprocess the text before tokenization.
 |
 |      Returns
 |      -------
 |      preprocessor: callable
 |            A function to preprocess the text before tokenization.
 |
 |  build_tokenizer(self)
 |      Return a function that splits a string into a sequence of tokens.
 |
 |      Returns
 |      -------
 |      tokenizer: callable
 |            A function to split a string into a sequence of tokens.
 |
 |  decode(self, doc)
 |      Decode the input into a string of unicode symbols.
 |
 |      The decoding strategy depends on the vectorizer parameters.
 |
 |      Parameters
 |      ----------
 |      doc : bytes or str
 |          The string to decode.
 |
 |      Returns
 |      -------
 |      doc: str
 |          A string of unicode symbols.
 |
 |  get_stop_words(self)
 |      Build or fetch the effective stop words list.
 |
 |      Returns
 |      -------
 |      stop_words: list or None
 |              A list of stop words.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from _VectorizerMixin:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |      Helper for pickle.
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  __sklearn_clone__(self)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : dict
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as :class:`~sklearn.pipeline.Pipeline`). The latter have
 |      parameters of the form ``<component>__<parameter>`` so that it's
 |      possible to update each component of a nested object.
 |
 |      Parameters
 |      ----------
 |      **params : dict
 |          Estimator parameters.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.utils._metadata_requests._MetadataRequester:
 |
 |  get_metadata_routing(self)
 |      Get metadata routing of this object.
 |
 |      Please check :ref:`User Guide <metadata_routing>` on how the routing
 |      mechanism works.
 |
 |      Returns
 |      -------
 |      routing : MetadataRequest
 |          A :class:`~sklearn.utils.metadata_routing.MetadataRequest` encapsulating
 |          routing information.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from sklearn.utils._metadata_requests._MetadataRequester:
 |
 |  __init_subclass__(**kwargs)
 |      Set the ``set_{method}_request`` methods.
 |
 |      This uses PEP-487 [1]_ to set the ``set_{method}_request`` methods. It
 |      looks for the information available in the set default values which are
 |      set using ``__metadata_request__*`` class attributes, or inferred
 |      from method signatures.
 |
 |      The ``__metadata_request__*`` class attributes are used when a method
 |      does not explicitly accept a metadata through its arguments or if the
 |      developer would like to specify a request value for those metadata
 |      which are different from the default ``None``.
 |
 |      References
 |      ----------
 |      .. [1] https://www.python.org/dev/peps/pep-0487

In [13]:
vectorizer = CountVectorizer()

In [14]:
vectorizer.fit(X_train)

CountVectorizer()

In [15]:
dir(vectorizer)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'get_stop_words',
 'input',
 'inverse_transform',
 'lowercase',
 'max_df',
 'max_features',
 'min_df',
 'ngram_range',
 'preprocessor',
 'set_params',
 'stop_words',
 'strip_accents',
 'token_pattern',
 'tokenizer',
 'transform',
 'vocabulary',
 'vocabulary_']

In [16]:
vectorizer.vocabulary_

{'upgrad': 15,
 'is': 9,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'on': 12,
 'ethics': 4,
 'story': 14,
 'of': 11,
 'and': 0,
 'sholey': 13,
 'cinema': 1,
 'good': 5,
 'movie': 10}

## Removing Stop Words

In [17]:
vec = CountVectorizer(stop_words="english")

In [18]:
vec.fit(X_train)

CountVectorizer(stop_words='english')

In [19]:
vec.vocabulary_

{'upgrad': 11,
 'great': 5,
 'educational': 2,
 'institution': 7,
 'greatness': 6,
 'depends': 1,
 'ethics': 3,
 'story': 10,
 'sholey': 9,
 'cinema': 0,
 'good': 4,
 'movie': 8}

In [20]:
print(
    f"Features: {vec.get_feature_names_out()}, Length: {len(vec.get_feature_names_out())}"
)

Features: ['cinema' 'depends' 'educational' 'ethics' 'good' 'great' 'greatness'
 'institution' 'movie' 'sholey' 'story' 'upgrad'], Length: 12

In [21]:
X_transform = vec.transform(X_train)
str(X_transform)

'  (0, 2)\t1\n  (0, 5)\t1\n  (0, 7)\t1\n  (0, 11)\t1\n  (1, 1)\t1\n  (1, 2)\t1\n  (1, 3)\t1\n  (1, 6)\t1\n  (2, 2)\t1\n  (2, 3)\t1\n  (2, 5)\t1\n  (2, 6)\t1\n  (2, 10)\t1\n  (3, 0)\t1\n  (3, 5)\t1\n  (3, 9)\t1\n  (4, 1)\t1\n  (4, 4)\t2\n  (4, 8)\t1\n  (4, 10)\t1'

In [22]:
print(X_transform)

  (0, 2)	1
  (0, 5)	1
  (0, 7)	1
  (0, 11)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 6)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 6)	1
  (2, 10)	1
  (3, 0)	1
  (3, 5)	1
  (3, 9)	1
  (4, 1)	1
  (4, 4)	2
  (4, 8)	1
  (4, 10)	1

In [23]:
X_transform.toarray()

array([[0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0]])

In [24]:
pd.DataFrame(X_transform.toarray(), columns=vec.get_feature_names_out())

,cinema,depends,educational,ethics,good,great,greatness,institution,movie,sholey,story,upgrad
0,0,0,1,0,0,1,0,1,0,0,0,1
1,0,1,1,1,0,0,1,0,0,0,0,0
2,0,0,1,1,0,1,1,0,0,0,1,0
3,1,0,0,0,0,1,0,0,0,1,0,0
4,0,1,0,0,2,0,0,0,1,0,1,0

In [25]:
X_transform.shape

(5, 12)

## Doing it on test set

In [26]:
df_test = pd.read_csv("example_test.csv")

In [27]:
df_test

                            Document      Class
0  very good educational institution  education

In [28]:
df_test["Class"] = df_test["Class"].map({"cinema": 0, "education": 1})

In [29]:
test = df_test.values
X_test = test[:, 0]
y_test = test[:, 1]
print(X_test, y_test)

['very good educational institution'] [1]

In [30]:
X_test_transformed = vec.transform(X_test)
X_test_transformed

<1x12 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [31]:
print(X_test_transformed)

  (0, 2)	1
  (0, 4)	1
  (0, 7)	1

In [32]:
# convert to non-sparse array
X_test = X_test_transformed.toarray()
X_test

array([[0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0]])

Consider first 4 rows of the output: (0,2), (0,5), (0,7) and (0,11). It says that the first document (index 0) has 7th , 2nd , 5th and 11th 'word' present in the document, and that they appear only once in the document- indicated by the right hand column entry.


Similarly, consider the entry (4,4) (third from bottom). It says that the fifth document has the fifth word present twice. Indeed, the 5th word('good') appears twice in the 5th document.

## Building model using Multinomial Naive Bayes

In [33]:
# Importing
from sklearn.naive_bayes import MultinomialNB

# Instantiation
mnb = MultinomialNB()

# Fitting

mnb.fit(X_transform, y_train)

# Prediction

mnb.predict(X_test)

array([1])

In [34]:
mnb.predict_proba(X_test)

array([[0.32808399, 0.67191601]])

In [35]:
print("Probability of class cinema predicted:", mnb.predict_proba(X_test)[:, 0][0])
print("Probability of class education predicted:", mnb.predict_proba(X_test)[:, 1][0])

Probability of class cinema predicted: 0.3280839895013124
Probability of class education predicted: 0.6719160104986874

## Building model with Bernoulli

In [36]:
import sklearn.naive_bayes as naive_bayes

##  bernoulli instantiation

bn = naive_bayes.BernoulliNB()

## fit

bn.fit(X_transform, y_train)

bn.predict_proba(X_test)

array([[0.2326374, 0.7673626]])

In [43]:
a = 0.5
b_a = 0.99

b = b_a * a

In [44]:
b

0.495

In [45]:
a_b = b_a * a / b
a_b

1.0