In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.lib.deepreload import reload
from sklearn.preprocessing import MinMaxScaler, StandardScaler

from utilties.utils import display_info

In [3]:
df = pd.read_csv("data/house.csv")

In [3]:
df

     bedrooms  sqft_living    price
0           3         1340   313000
1           5         3650  2384000
2           3         1930   342000
3           3         2000   420000
4           4         1940   550000
..        ...          ...      ...
494         4         3040   647000
495         5         4530   950000
496         3         1370   185000
497         3         1940   335000
498         3         1040   210000

[499 rows x 3 columns]

In [4]:
X = df[["bedrooms", "sqft_living"]]
y = df["price"]

In [8]:
X_model = X.copy()
scaler = MinMaxScaler()
X_model = scaler.fit_transform(X_model)

In [9]:
X_model.shape

(499, 2)

In [25]:
type(X_model)

numpy.ndarray

In [26]:
display_info(X)

     bedrooms  sqft_living
0           3         1340
1           5         3650
2           3         1930
3           3         2000
4           4         1940
..        ...          ...
494         4         3040
495         5         4530
496         3         1370
497         3         1940
498         3         1040

[499 rows x 2 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   bedrooms     499 non-null    int64
 1   sqft_living  499 non-null    int64
dtypes: int64(2)
memory usage: 7.9 KB

None

In [17]:
from utilties.utils import removing_statistical_outliers

In [28]:
from utilties import utils


import nest_asyncio

nest_asyncio.apply()

In [29]:
utils.unique_values_percentage(df, ["bedrooms", "sqft_living"])

{'bedrooms':             column  Count  Percentage (%)
 bedrooms
 3         bedrooms    215       43.086172
 4         bedrooms    163       32.665331
 2         bedrooms     69       13.827655
 5         bedrooms     41        8.216433
 6         bedrooms      5        1.002004
 7         bedrooms      3        0.601202
 1         bedrooms      2        0.400802
 9         bedrooms      1        0.200401,
 'sqft_living':                   column  Count  Percentage (%)
 sqft_living
 1410         sqft_living      8        1.603206
 2000         sqft_living      8        1.603206
 1940         sqft_living      7        1.402806
 1920         sqft_living      5        1.002004
 3040         sqft_living      5        1.002004
 ...                  ...    ...             ...
 3370         sqft_living      1        0.200401
 2150         sqft_living      1        0.200401
 1440         sqft_living      1        0.200401
 1408         sqft_living      1        0.200401
 4530         sqft_living      1        0.200401

 [254 rows x 3 columns]}

In [52]:
def unique_values_percentage(df, columns):
    """
    A function to calculate the summary of categorical columns of a dataframe
        @param: df -> DataFrame
        @param: columns: list of categorical columns in the dataframe
        @returns: dictionary of summary of unique value counts and their percentages
    >>> x = pd.DataFrame({'temp':['hot','hot','cool']})

    """
    results = pd.DataFrame()
    for column in columns:
        # Count unique values and calculate percentages
        value_counts = df[column].value_counts()
        percentages = df[column].value_counts(normalize=True) * 100

        # Combine counts and percentages into a DataFrame
        unique_summary = pd.DataFrame(
            {"column": column, "Count": value_counts, "Percentage (%)": percentages}
        ).sort_values(by="Count", ascending=False)

        # Add the result to the dictionary
        # display(pd.concat([results,unique_summary]))
        results = pd.concat([results, unique_summary])

    return results

In [49]:
x = unique_values_percentage(X, X.columns.tolist())

In [50]:
x

{'bedrooms':             column  Count  Percentage (%)
 bedrooms
 3         bedrooms    215       43.086172
 4         bedrooms    163       32.665331
 2         bedrooms     69       13.827655
 5         bedrooms     41        8.216433
 6         bedrooms      5        1.002004
 7         bedrooms      3        0.601202
 1         bedrooms      2        0.400802
 9         bedrooms      1        0.200401,
 'sqft_living':                   column  Count  Percentage (%)
 sqft_living
 1410         sqft_living      8        1.603206
 2000         sqft_living      8        1.603206
 1940         sqft_living      7        1.402806
 3040         sqft_living      5        1.002004
 1390         sqft_living      5        1.002004
 ...                  ...    ...             ...
 3810         sqft_living      1        0.200401
 2400         sqft_living      1        0.200401
 3780         sqft_living      1        0.200401
 1352         sqft_living      1        0.200401
 4530         sqft_living      1        0.200401

 [254 rows x 3 columns]}

In [51]:
X["bedrooms"].describe()

count    499.000000
mean       3.410822
std        0.949299
min        1.000000
25%        3.000000
50%        3.000000
75%        4.000000
max        9.000000
Name: bedrooms, dtype: float64

In [16]:
X_1 = X["bedrooms"].copy()

In [18]:
X.merge(X_1, how="inner")

       bedrooms  sqft_living
0             3         1340
1             3         1340
2             3         1340
3             3         1340
4             3         1340
...         ...          ...
79270         3         1040
79271         3         1040
79272         3         1040
79273         3         1040
79274         3         1040

[79275 rows x 2 columns]

## Part 4: Forward pass matrix multiplication
![](multiple_neurons.png)

![](Matrix.gif)

This network can be described as follows:

- Input vector = $X = (x1,x2)$
- Weight Matrix (hidden layer) = $$W^1 = \begin{bmatrix}
w^1_{11}&&w^1_{12}\ \
    w^1_{21}&&w^1_{22}\ \
    \end{bmatrix}
$$
*note the subscripts are being mapped to weights in the figure

- Bias/offset Matrix (hidden layer) = $$
B^1_0 = \begin{bmatrix}
b^1_{1}\ \
    b^1_{2}\ \
    \end{bmatrix}
$$

Now the forward pass for the hidden layer can be described as

$$W^1 \times X^T + B^1_0= Z^1 = \begin{bmatrix}
z^1_{1}\ \
    z^1_{2}\ \
    \end{bmatrix}
$$

Applying the activation function $f$ over the matrix $Z$ will complete the forward pass.

$$f(W^1 \times X^T + B^1_0)= f(Z^1) = f(\begin{bmatrix}
z^1_{1}\ \
    z^1_{2}\ \
    \end{bmatrix}) =
\begin{bmatrix}
f(z^1_{1})\ \
    f(z^1_{2})\ \
    \end{bmatrix}
=
\begin{bmatrix}
h^1_1\ \
    h^1_2\ \
    \end{bmatrix}
= H^1
$$

For the output layer:

- The weight matrix is $$W^2 = \begin{bmatrix}
w^2_{11}&&w^2_{12}\ \
    \end{bmatrix}
$$

- The bias/offset matrix is $$B^2_0 = \begin{bmatrix}
b^2_{1}\ \
    \end{bmatrix}
$$

Now the forward pass can be written as:


$$ B_0^2+W^2 \times H^1$$