In [1]:
# Import libraries
import pandas as pd

In [2]:
# Load the collision data
# Use the sample dataset present in the script and save it in the same directory as the notebook
collisions = pd.read_csv("sample_collisions.csv")
print("Collisions data loaded:", collisions.shape)

# Load the parties (drivers/passengers) data
parties = pd.read_csv("sample_parties.csv")
print("Parties data loaded:", parties.shape)

Collisions data loaded: (935791, 65)
Parties data loaded: (1866917, 24)

In [3]:
# Real-world note:
# In real data projects, the transformation stage often takes 70–80% of the total effort.
# This includes cleaning column names, fixing formats, merging files, and filling missing values.
# These steps are essential before any meaningful analysis can be done.

In [4]:
# Step 1: Clean column names (make them lowercase and replace spaces with underscores)
collisions.columns = collisions.columns.str.lower().str.strip().str.replace(" ", "_")
parties.columns = parties.columns.str.lower().str.strip().str.replace(" ", "_")

In [5]:
print("Step 1: Cleaned column names (Collisions)")
display(collisions.head(2))
display(collisions.tail(2))

Step 1: Cleaned column names (Collisions)

,case_id,jurisdiction,officer_id,reporting_district,chp_shift,population,county_city_location,county_location,special_condition,beat_type,...,pedestrian_injured_count,bicyclist_killed_count,bicyclist_injured_count,motorcyclist_killed_count,motorcyclist_injured_count,latitude,longitude,collision_date,collision_time,process_date
0,8000993.0,1942.0,39335,1676,not chp,>250000,1942,los angeles,0.0,not chp,...,0,0,0,0,0.0,NaN,NaN,2016-03-20,16:30:00,2016-03-30
1,4232117.0,3008.0,1284,Z2,not chp,100000 to 250000,3008,orange,0.0,not chp,...,0,0,0,0,0.0,NaN,NaN,2009-04-13,18:24:00,2009-11-30

,case_id,jurisdiction,officer_id,reporting_district,chp_shift,population,county_city_location,county_location,special_condition,beat_type,...,pedestrian_injured_count,bicyclist_killed_count,bicyclist_injured_count,motorcyclist_killed_count,motorcyclist_injured_count,latitude,longitude,collision_date,collision_time,process_date
935789,8524097.0,3313.0,1489,1,not chp,>250000,3313,riverside,0.0,not chp,...,0,0,0,0,0.0,34.01604,-117.35728,2017-12-09,15:02:00,2018-04-27
935790,8616128.0,3701.0,CB5485,NaN,not chp,50000 to 100000,3701,san diego,0.0,not chp,...,0,0,0,0,0.0,NaN,NaN,2018-04-23,04:45:00,2018-05-16

In [6]:
print("Step 1: Cleaned column names (Parties)")
display(parties.head(2))
display(parties.tail(2))

Step 1: Cleaned column names (Parties)

,id,case_id,party_number,party_type,at_fault,party_sex,party_age,party_sobriety,direction_of_travel,party_safety_equipment_1,...,other_associate_factor_1,party_number_killed,party_number_injured,movement_preceding_collision,vehicle_year,vehicle_make,statewide_vehicle_type,chp_vehicle_type_towing,chp_vehicle_type_towed,party_race
0,1292305,4843348.0,1,driver,1,male,28.0,had not been drinking,south,lap/shoulder harness used,...,inattention,0,0,making right turn,1974.0,chevrolet,passenger car,NaN,NaN,NaN
1,3252679,5965300.0,2,driver,0,male,53.0,had not been drinking,south,air bag not deployed,...,entering/leaving ramp,0,0,proceeding straight,2000.0,toyota,passenger car,"passenger car, station",00,hispanic

,id,case_id,party_number,party_type,at_fault,party_sex,party_age,party_sobriety,direction_of_travel,party_safety_equipment_1,...,other_associate_factor_1,party_number_killed,party_number_injured,movement_preceding_collision,vehicle_year,vehicle_make,statewide_vehicle_type,chp_vehicle_type_towing,chp_vehicle_type_towed,party_race
1866915,9985658,9.131464e+07,2,driver,1,female,44.0,impairment unknown,north,air bag not deployed,...,none apparent,0,0,proceeding straight,2003.0,kia,passenger car,sport utility vehicle,NaN,white
1866916,8407648,4.502011e+18,1,driver,1,male,45.0,had not been drinking,west,lap/shoulder harness used,...,none apparent,0,0,proceeding straight,1994.0,chevrolet,pickup or panel truck,0.0,0.0,NaN

In [7]:
# Step 2: Select only relevant columns
collisions_subset = collisions[["case_id", "county_location"]]
parties_subset = parties[["case_id", "party_age"]]

In [8]:
print("Step 2: Selected columns from collisions")
display(collisions_subset.head(2))
display(collisions_subset.tail(2))

Step 2: Selected columns from collisions

     case_id county_location
0  8000993.0     los angeles
1  4232117.0          orange

          case_id county_location
935789  8524097.0       riverside
935790  8616128.0       san diego

In [9]:
print("Step 2: Selected columns from parties")
display(parties_subset.head(2))
display(parties_subset.tail(2))

Step 2: Selected columns from parties

     case_id  party_age
0  4843348.0       28.0
1  5965300.0       53.0

              case_id  party_age
1866915  9.131464e+07       44.0
1866916  4.502011e+18       45.0

In [10]:
# Step 3: Merge on 'case_id'
merged = pd.merge(collisions_subset, parties_subset, on="case_id", how="inner")

In [11]:
print("Step 3: After merge (Collisions + Parties)")
display(merged.head(2))
display(merged.tail(2))

Step 3: After merge (Collisions + Parties)

      case_id county_location  party_age
0   1665179.0     los angeles       48.0
1  90608430.0     los angeles       38.0

           case_id county_location  party_age
185600  90647037.0      sacramento       29.0
185601   1867187.0     los angeles       23.0

In [12]:
# Step 4: Fix data types
merged["party_age"] = pd.to_numeric(merged["party_age"], errors="coerce")

print("Step 4: Converted party_age to numeric")
display(merged.head(2))
display(merged.tail(2))

Step 4: Converted party_age to numeric

      case_id county_location  party_age
0   1665179.0     los angeles       48.0
1  90608430.0     los angeles       38.0

           case_id county_location  party_age
185600  90647037.0      sacramento       29.0
185601   1867187.0     los angeles       23.0

In [13]:
# Step 5: Fill missing values
merged["party_age"] = merged["party_age"].fillna(-1)

print("Step 5: Filled missing party_age values with -1")
display(merged.head(2))
display(merged.tail(2))

Step 5: Filled missing party_age values with -1

      case_id county_location  party_age
0   1665179.0     los angeles       48.0
1  90608430.0     los angeles       38.0

           case_id county_location  party_age
185600  90647037.0      sacramento       29.0
185601   1867187.0     los angeles       23.0

In [14]:
# Step 6: Standardize text (title-case for county_location)
merged["county_location"] = merged["county_location"].str.title().str.strip()

print("Step 6: Standardized county_location text")
display(merged.head(2))
display(merged.tail(2))

Step 6: Standardized county_location text

      case_id county_location  party_age
0   1665179.0     Los Angeles       48.0
1  90608430.0     Los Angeles       38.0

           case_id county_location  party_age
185600  90647037.0      Sacramento       29.0
185601   1867187.0     Los Angeles       23.0