You have two data sets, each containing different columns of information regarding the employees of a company. The two data sets have a varying number of rows/observations. Dataset-1 contains information on Name, Age, and Salary against Employee ID. Dataset-2 contains information on Education and Experience against EmployeeID. It is unknown why the data sets have varying rows, i.e. why some employees were missed while collecting the data for each of the data sets. Employee ID is the identifier and thus the common column in both the data sets.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df_1 = {"col1": [1, 2, 3, 4], "col2": [5, 6, 7, 8]}
df_2 = {"col1": [11, 12, 13, 14], "col2": [15, 16, 17, 18]}

In [9]:
weather = pd.read_csv("weatherdata.csv")

In [12]:
location = pd.read_csv("locationsandstates.csv")

In [19]:
weather.merge(location, on="Location", how="left")

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,State
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,New South Wales
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,New South Wales
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,New South Wales
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,New South Wales
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,New South Wales
...,...,...,...,...,...,...,...,...,...,...
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,NaN
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,NaN
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,NaN
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,NaN
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,NaN

In [6]:
weather

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0
...,...,...,...,...,...,...,...,...,...
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0

In [15]:
location

          Location               State
0           Sydney    New South Wales
1           Albury    New South Wales
2         Armidale    New South Wales
3         Bathurst    New South Wales
4   Blue Mountains    New South Wales
..             ...                 ...
72      Kalgoorlie   Western Australia
73        Karratha   Western Australia
74        Mandurah   Western Australia
75      Rockingham   Western Australia
76            Rock  Western Australia1

[77 rows x 2 columns]

In [8]:
weather["Location"].value_counts()

Location
Canberra            3418
Sydney              3337
Perth               3193
Darwin              3192
Hobart              3188
Brisbane            3161
Adelaide            3090
Bendigo             3034
Townsville          3033
AliceSprings        3031
MountGambier        3030
Launceston          3028
Ballarat            3028
Albany              3016
Albury              3011
PerthAirport        3009
MelbourneAirport    3009
Mildura             3007
SydneyAirport       3005
Nuriootpa           3002
Sale                3000
Watsonia            2999
Tuggeranong         2998
Portland            2996
Woomera             2990
Cairns              2988
Cobar               2988
Wollongong          2983
GoldCoast           2980
WaggaWagga          2976
Penrith             2964
NorfolkIsland       2964
SalmonGums          2955
Newcastle           2955
CoffsHarbour        2953
Witchcliffe         2952
Richmond            2951
Dartmoor            2943
NorahHead           2929
BadgerysCreek       2928
MountGinini         2907
Moree               2854
Walpole             2819
PearceRAAF          2762
Williamtown         2553
Melbourne           2435
Nhil                1569
Katherine           1559
Uluru               1521
Name: count, dtype: int64

In [ ]:
weather.me