In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Graded1.csv")

In [3]:
df

    S.No Class        Freq 1        Freq 2        Freq 3        Freq 4
0      2   Ham         reply          data        report  presentation
1      3   Ham        report  presentation          file    end of day
2      5   Ham       meeting     timelines       limited     documents
3      8   Ham  presentation    end of day          data        report
4      9   Ham         reply          data  presentation         click
5     12   Ham       meeting    end of day       weekend          data
6     14   Ham        report  presentation          file    end of day
7     15   Ham          free     timelines         reply         offer
8      1  Spam          free           buy       limited         hurry
9      4  Spam       limited          file           buy         click
10     6  Spam         hurry          data           buy         stock
11     7  Spam       limited           sex         click        viagra
12    10  Spam          free         reply       weekend         click
13    11  Spam       limited         click          free         hurry
14    13  Spam         hurry       weekend         stock         offer

In [5]:
df = df.sort_values(by="Class")

In [6]:
df

    S.No Class        Freq 1        Freq 2        Freq 3        Freq 4
0      2   Ham         reply          data        report  presentation
1      3   Ham        report  presentation          file    end of day
2      5   Ham       meeting     timelines       limited     documents
3      8   Ham  presentation    end of day          data        report
4      9   Ham         reply          data  presentation         click
5     12   Ham       meeting    end of day       weekend          data
6     14   Ham        report  presentation          file    end of day
7     15   Ham          free     timelines         reply         offer
8      1  Spam          free           buy       limited         hurry
9      4  Spam       limited          file           buy         click
10     6  Spam         hurry          data           buy         stock
11     7  Spam       limited           sex         click        viagra
12    10  Spam          free         reply       weekend         click
13    11  Spam       limited         click          free         hurry
14    13  Spam         hurry       weekend         stock         offer

In [35]:
df = pd.read_csv("naive.csv", delimiter="\t")

In [36]:
df

   Doc.No.                                Document Class
0        0           Coffee Tea Soup Coffee Coffee   Hot
1        1    Coffee is hot and so is Soup and Tea   Hot
2        2  Espresso is a hot Coffee and not a Tea   Hot
3        3          Coffee is neither Tea nor Soup   Hot
4        4   Sprite Pepsi Cold Coffee and cold Tea  Cold

In [37]:
from sklearn.naive_bayes import BernoulliNB

In [38]:
df["Class"] = df["Class"].map({"Hot": 1, "Cold": 0})

In [39]:
X = df["Document"]
y = df["Class"]

In [60]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words="english")

In [61]:
vectorizer.fit(X)

CountVectorizer(stop_words='english')

In [62]:
len(set(vectorizer.vocabulary_.keys()))

8

In [63]:
X_transform = vectorizer.transform(X)

In [64]:
print(X_transform)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 19 stored elements and shape (5, 8)>
  Coords	Values
  (0, 0)	3
  (0, 5)	1
  (0, 7)	1
  (1, 0)	1
  (1, 3)	1
  (1, 5)	1
  (1, 7)	1
  (2, 0)	1
  (2, 2)	1
  (2, 3)	1
  (2, 7)	1
  (3, 0)	1
  (3, 5)	1
  (3, 7)	1
  (4, 0)	1
  (4, 1)	2
  (4, 4)	1
  (4, 6)	1
  (4, 7)	1

In [65]:
import sklearn.naive_bayes as naive_bayes

# Instantiation
mnb = naive_bayes.MultinomialNB()

mnb.fit(X_transform, y)

mnb.predict_proba(X_transform)

array([[0.00855892, 0.99144108],
       [0.02014855, 0.97985145],
       [0.03950121, 0.96049879],
       [0.03473506, 0.96526494],
       [0.96310726, 0.03689274]])

In [66]:
vectorizer.vocabulary_

{'coffee': 0,
 'tea': 7,
 'soup': 5,
 'hot': 3,
 'espresso': 2,
 'sprite': 6,
 'pepsi': 4,
 'cold': 1}

In [67]:
pd.DataFrame(X_transform.toarray(), columns=vectorizer.get_feature_names_out())

   coffee  cold  espresso  hot  pepsi  soup  sprite  tea
0       3     0         0    0      0     1       0    1
1       1     0         0    1      0     1       0    1
2       1     0         1    1      0     0       0    1
3       1     0         0    0      0     1       0    1
4       1     2         0    0      1     0       1    1

In [50]:
vectorizer.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'preprocessor': None,
 'stop_words': 'english',
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}