ou're given two lists, the first of which contains the name of some people and the second contains their corresponding 'response'. These lists have been converted to a dataframe.
Now, the values that the 'response' variable can take are ‘Yes’, ‘No’, and ‘Maybe’. Write a code to map these variables to the values ‘1.0’, ‘0.0’, and ‘0.5’.

Note: It also might happen the the first letter of the three responses are not in uppercase, i.e. you might also have the values 'yes', 'no', and 'maybe' in the dataframe. So make sure you handle that in your code.
['Reetesh', 'Shruti', 'Kaustubh', 'Vikas', 'Mahima', 'Akshay']
['No', 'Maybe', 'yes', 'Yes', 'maybe', 'Yes']

In [14]:
name = ["Reetesh", "Shruti", "Kaustubh", "Vikas", "Mahima", "Akshay"]
response = ["No", "Maybe", "yes", "Yes", "maybe", "Yes"]
import pandas as pd

In [17]:
response = [x.lower() for x in response]
df = pd.DataFrame({"name": name, "response": response})
responses_dict = {"yes": 1, "no": 0, "maybe": 0.5}
df["response"] = df["response"].map(lambda x: responses_dict[x])

In [18]:
df

       name  response
0   Reetesh       0.0
1    Shruti       0.5
2  Kaustubh       1.0
3     Vikas       1.0
4    Mahima       0.5
5    Akshay       1.0

In [9]:
df

      names  responses
0   Reetesh        0.0
1    Shruti        0.5
2  Kaustubh        1.0
3     Vikas        1.0
4    Mahima        0.5
5    Akshay        1.0