In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
#from torch.utils.data.dataset import _T_co
torch.manual_seed(0)
import os
os.environ["PYTORCH_MPS_HIGH_WATERMARK_RATIO"] = "0.0"

In [3]:
from transformers import DistilBertTokenizerFast,DistilBertForSequenceClassification

In [4]:
# device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.mps.is_available() else "cpu")

In [5]:

device="cpu"

In [6]:
RANDOM_SEED = 0
NUM_EPOCHS = 3
#torch.manual_seed(RANDOM_SEED) # generator function

In [7]:
df = pd.read_csv('sample30.csv')

In [8]:
df

,id,brand,categories,manufacturer,name,reviews_date,reviews_didPurchase,reviews_doRecommend,reviews_rating,reviews_text,reviews_title,reviews_userCity,reviews_userProvince,reviews_username,user_sentiment
0,AV13O1A8GV-KLJ3akUyj,Universal Music,"Movies, Music & Books,Music,R&b,Movies & TV,Mo...",Universal Music Group / Cash Money,Pink Friday: Roman Reloaded Re-Up (w/dvd),2012-11-30T06:21:45.000Z,NaN,NaN,5,i love this album. it's very good. more to the...,Just Awesome,Los Angeles,NaN,joshua,Positive
1,AV14LG0R-jtxr-f38QfS,Lundberg,"Food,Packaged Foods,Snacks,Crackers,Snacks, Co...",Lundberg,Lundberg Organic Cinnamon Toast Rice Cakes,2017-07-09T00:00:00.000Z,True,NaN,5,Good flavor. This review was collected as part...,Good,NaN,NaN,dorothy w,Positive
2,AV14LG0R-jtxr-f38QfS,Lundberg,"Food,Packaged Foods,Snacks,Crackers,Snacks, Co...",Lundberg,Lundberg Organic Cinnamon Toast Rice Cakes,2017-07-09T00:00:00.000Z,True,NaN,5,Good flavor.,Good,NaN,NaN,dorothy w,Positive
3,AV16khLE-jtxr-f38VFn,K-Y,"Personal Care,Medicine Cabinet,Lubricant/Sperm...",K-Y,K-Y Love Sensuality Pleasure Gel,2016-01-06T00:00:00.000Z,False,False,1,I read through the reviews on here before look...,Disappointed,NaN,NaN,rebecca,Negative
4,AV16khLE-jtxr-f38VFn,K-Y,"Personal Care,Medicine Cabinet,Lubricant/Sperm...",K-Y,K-Y Love Sensuality Pleasure Gel,2016-12-21T00:00:00.000Z,False,False,1,My husband bought this gel for us. The gel cau...,Irritation,NaN,NaN,walker557,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",L'oreal Paris,L'or233al Paris Elvive Extraordinary Clay Reba...,2017-01-23T00:00:00.000Z,False,True,5,I got this conditioner with Influenster to try...,Softness!!,NaN,NaN,laurasnchz,Positive
29996,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",L'oreal Paris,L'or233al Paris Elvive Extraordinary Clay Reba...,2017-01-27T00:00:00.000Z,False,True,5,"I love it , I received this for review purpose...",I love it,NaN,NaN,scarlepadilla,Positive
29997,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",L'oreal Paris,L'or233al Paris Elvive Extraordinary Clay Reba...,2017-01-21T00:00:00.000Z,False,True,5,First of all I love the smell of this product....,Hair is so smooth after use,NaN,NaN,liviasuexo,Positive
29998,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",L'oreal Paris,L'or233al Paris Elvive Extraordinary Clay Reba...,2017-01-11T00:00:00.000Z,False,True,5,I received this through Influenster and will n...,Perfect for my oily hair!,NaN,NaN,ktreed95,Positive
29999,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",L'oreal Paris,L'or233al Paris Elvive Extraordinary Clay Reba...,2017-01-19T00:00:00.000Z,False,True,5,I received this product complimentary from inf...,Conditioned into healthy,NaN,NaN,kcoopxoxo,Positive

In [9]:
#todo convert to graph nn
device = "cpu"

In [10]:
reviews = df[['id','brand','categories','reviews_text','reviews_title','reviews_rating','user_sentiment']]

In [11]:
reviews.dropna(inplace=True)

In [12]:
reviews

,id,brand,categories,reviews_text,reviews_title,reviews_rating,user_sentiment
0,AV13O1A8GV-KLJ3akUyj,Universal Music,"Movies, Music & Books,Music,R&b,Movies & TV,Mo...",i love this album. it's very good. more to the...,Just Awesome,5,Positive
1,AV14LG0R-jtxr-f38QfS,Lundberg,"Food,Packaged Foods,Snacks,Crackers,Snacks, Co...",Good flavor. This review was collected as part...,Good,5,Positive
2,AV14LG0R-jtxr-f38QfS,Lundberg,"Food,Packaged Foods,Snacks,Crackers,Snacks, Co...",Good flavor.,Good,5,Positive
3,AV16khLE-jtxr-f38VFn,K-Y,"Personal Care,Medicine Cabinet,Lubricant/Sperm...",I read through the reviews on here before look...,Disappointed,1,Negative
4,AV16khLE-jtxr-f38VFn,K-Y,"Personal Care,Medicine Cabinet,Lubricant/Sperm...",My husband bought this gel for us. The gel cau...,Irritation,1,Negative
...,...,...,...,...,...,...,...
29995,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",I got this conditioner with Influenster to try...,Softness!!,5,Positive
29996,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...","I love it , I received this for review purpose...",I love it,5,Positive
29997,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",First of all I love the smell of this product....,Hair is so smooth after use,5,Positive
29998,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",I received this through Influenster and will n...,Perfect for my oily hair!,5,Positive
29999,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",I received this product complimentary from inf...,Conditioned into healthy,5,Positive

## finetuning for sentiment classification

In [13]:
reviews['reviews']=reviews['reviews_title'].add(" ").add(reviews["reviews_text"])
reviews.drop(['reviews_title','reviews_text'], axis=1, inplace=True)

In [14]:
reviews

,id,brand,categories,reviews_rating,user_sentiment,reviews
0,AV13O1A8GV-KLJ3akUyj,Universal Music,"Movies, Music & Books,Music,R&b,Movies & TV,Mo...",5,Positive,Just Awesome i love this album. it's very good...
1,AV14LG0R-jtxr-f38QfS,Lundberg,"Food,Packaged Foods,Snacks,Crackers,Snacks, Co...",5,Positive,Good Good flavor. This review was collected as...
2,AV14LG0R-jtxr-f38QfS,Lundberg,"Food,Packaged Foods,Snacks,Crackers,Snacks, Co...",5,Positive,Good Good flavor.
3,AV16khLE-jtxr-f38VFn,K-Y,"Personal Care,Medicine Cabinet,Lubricant/Sperm...",1,Negative,Disappointed I read through the reviews on her...
4,AV16khLE-jtxr-f38VFn,K-Y,"Personal Care,Medicine Cabinet,Lubricant/Sperm...",1,Negative,Irritation My husband bought this gel for us. ...
...,...,...,...,...,...,...
29995,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",5,Positive,Softness!! I got this conditioner with Influen...
29996,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",5,Positive,"I love it I love it , I received this for revi..."
29997,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",5,Positive,Hair is so smooth after use First of all I lov...
29998,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",5,Positive,Perfect for my oily hair! I received this thro...
29999,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",5,Positive,Conditioned into healthy I received this produ...

In [15]:
reviews['user_sentiment']=reviews['user_sentiment'].map({'Positive':1,'Negative':0})

In [16]:
reviews

,id,brand,categories,reviews_rating,user_sentiment,reviews
0,AV13O1A8GV-KLJ3akUyj,Universal Music,"Movies, Music & Books,Music,R&b,Movies & TV,Mo...",5,1,Just Awesome i love this album. it's very good...
1,AV14LG0R-jtxr-f38QfS,Lundberg,"Food,Packaged Foods,Snacks,Crackers,Snacks, Co...",5,1,Good Good flavor. This review was collected as...
2,AV14LG0R-jtxr-f38QfS,Lundberg,"Food,Packaged Foods,Snacks,Crackers,Snacks, Co...",5,1,Good Good flavor.
3,AV16khLE-jtxr-f38VFn,K-Y,"Personal Care,Medicine Cabinet,Lubricant/Sperm...",1,0,Disappointed I read through the reviews on her...
4,AV16khLE-jtxr-f38VFn,K-Y,"Personal Care,Medicine Cabinet,Lubricant/Sperm...",1,0,Irritation My husband bought this gel for us. ...
...,...,...,...,...,...,...
29995,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",5,1,Softness!! I got this conditioner with Influen...
29996,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",5,1,"I love it I love it , I received this for revi..."
29997,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",5,1,Hair is so smooth after use First of all I lov...
29998,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",5,1,Perfect for my oily hair! I received this thro...
29999,AVpfW8y_LJeJML437ySW,L'oreal Paris,"Beauty,Hair Care,Shampoo & Conditioner,Holiday...",5,1,Conditioned into healthy I received this produ...

In [18]:
reviews.to_csv('reviews.csv',index=False)

In [19]:
train_reviews = reviews.iloc[:len(reviews)//8]

In [20]:
train_reviews

,id,brand,categories,reviews_rating,user_sentiment,reviews
0,AV13O1A8GV-KLJ3akUyj,Universal Music,"Movies, Music & Books,Music,R&b,Movies & TV,Mo...",5,1,Just Awesome i love this album. it's very good...
1,AV14LG0R-jtxr-f38QfS,Lundberg,"Food,Packaged Foods,Snacks,Crackers,Snacks, Co...",5,1,Good Good flavor. This review was collected as...
2,AV14LG0R-jtxr-f38QfS,Lundberg,"Food,Packaged Foods,Snacks,Crackers,Snacks, Co...",5,1,Good Good flavor.
3,AV16khLE-jtxr-f38VFn,K-Y,"Personal Care,Medicine Cabinet,Lubricant/Sperm...",1,0,Disappointed I read through the reviews on her...
4,AV16khLE-jtxr-f38VFn,K-Y,"Personal Care,Medicine Cabinet,Lubricant/Sperm...",1,0,Irritation My husband bought this gel for us. ...
...,...,...,...,...,...,...
367,AV1l8zRZvKc47QAVhnAv,Olay,"Personal Care,Skin Care,Anti-Aging,Beauty,Face...",5,1,Wonderfully hydrating I have been using this c...
368,AV1l8zRZvKc47QAVhnAv,Olay,"Personal Care,Skin Care,Anti-Aging,Beauty,Face...",5,1,Hydration PLUS My skin was so dry dull before ...
369,AV1l8zRZvKc47QAVhnAv,Olay,"Personal Care,Skin Care,Anti-Aging,Beauty,Face...",5,1,The best hydration product I have used in year...
370,AV1l8zRZvKc47QAVhnAv,Olay,"Personal Care,Skin Care,Anti-Aging,Beauty,Face...",5,0,amazing product Ive been using Regenerist Deep...
371,AV1l8zRZvKc47QAVhnAv,Olay,"Personal Care,Skin Care,Anti-Aging,Beauty,Face...",5,1,Great with dry skin I stay out side a lot of t...

In [21]:
validation_reviews = reviews.iloc[len(reviews)//80:len(reviews)//40]

In [22]:
test_reviews = reviews.iloc[len(reviews)//40:len(reviews)//40+len(reviews)//100]

In [23]:
len(test_reviews)

298

In [24]:
len(validation_reviews)

373

In [25]:
len(train_reviews)

372

In [26]:
model = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

In [27]:
from transformers import DistilBertTokenizerFast

# Load the standard, official DistilBERT tokenizer
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

In [28]:
list(train_reviews['reviews'])[:2]

["Just Awesome i love this album. it's very good. more to the hip hop side than her current pop sound.. SO HYPE! i listen to this everyday at the gym! i give it 5star rating all the way. her metaphors are just crazy.",
 'Good Good flavor. This review was collected as part of a promotion.']

In [29]:
x=list(train_reviews['reviews'].values)[:2]

In [30]:


from transformers import PreTrainedModel

In [31]:
dir(PreTrainedModel)

['T_destination',
 '__annotate_func__',
 '__annotations__',
 '__annotations_cache__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adjust_bias',
 '_adjust_missing_and_unexpected_keys',
 '_apply',
 '_auto_class',
 '_backward_compatibility_gradient_checkpointing',
 '_call_impl',
 '_can_compile_fullgraph',
 '_can_record_outputs',
 '_can_set_attn_implementation',
 '_can_set_experts_implementation',
 '_check_and_adjust_attn_implementation',
 '_check_and_adjust_experts_implementation',
 '_compatible_flash_implementations',
 '_compiled_call_impl',
 '_copy_lm_head_original_to_resized',
 '_default_compile_config',
 '_device_mesh',
 '_dispatch_accelerate_model',
 '_ep_plan',
 '_finalize_model_loading',
 '_flash_attn_can_dispatch',
 '_flash_attn_import_error',
 '_flex_attn_can_dispatch',
 '_from_config',
 '_fsdp_plan',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_dtype_plan',
 '_get_files_timestamps',
 '_get_name',
 '_get_resized_embeddings',
 '_get_resized_lm_head',
 '_grouped_mm_can_dispatch',
 '_hf_peft_config_loaded',
 '_init_added_embeddings_weights_with_mean',
 '_init_added_lm_head_bias_with_mean',
 '_init_added_lm_head_weights_with_mean',
 '_init_weights',
 '_initialize_missing_keys',
 '_initialize_weights',
 '_input_embed_layer',
 '_is_stateful',
 '_keep_in_fp32_modules',
 '_keep_in_fp32_modules_strict',
 '_keys_to_ignore_on_load_missing',
 '_keys_to_ignore_on_load_unexpected',
 '_keys_to_ignore_on_save',
 '_load_from_state_dict',
 '_load_pretrained_model',
 '_maybe_warn_non_full_backward_hook',
 '_move_missing_keys_from_meta_to_device',
 '_named_members',
 '_no_split_modules',
 '_pp_plan',
 '_prepare_peft_hotswap_kwargs',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_resize_token_embeddings',
 '_save_to_state_dict',
 '_sdpa_can_dispatch',
 '_set_gradient_checkpointing',
 '_skip_keys_device_placement',
 '_slow_forward',
 '_supports_attention_backend',
 '_supports_context_parallel',
 '_supports_flash_attn',
 '_supports_flex_attn',
 '_supports_sdpa',
 '_tied_weights_keys',
 '_tp_plan',
 '_tp_size',
 '_upload_modified_files',
 '_version',
 '_wrapped_call_impl',
 'active_adapters',
 'add_adapter',
 'add_model_tags',
 'add_module',
 'apply',
 'barrier_after_gathered_checkpoint_save',
 'base_model',
 'base_model_prefix',
 'bfloat16',
 'buffers',
 'call_super_init',
 'can_generate',
 'can_record_outputs',
 'children',
 'compile',
 'config_class',
 'cpu',
 'cuda',
 'delete_adapter',
 'dequantize',
 'device',
 'disable_adapters',
 'disable_input_require_grads',
 'double',
 'dtype',
 'dummy_inputs',
 'dump_patches',
 'enable_adapters',
 'enable_input_require_grads',
 'enable_peft_hotswap',
 'eval',
 'extra_repr',
 'float',
 'forward',
 'from_pretrained',
 'fsdp_plan',
 'gather_sharded_state_dict_for_save',
 'generation_config_class',
 'get_adapter_state_dict',
 'get_buffer',
 'get_compiled_call',
 'get_correct_attn_implementation',
 'get_correct_experts_implementation',
 'get_decoder',
 'get_encoder',
 'get_expanded_tied_weights_keys',
 'get_experts_implementation',
 'get_extra_state',
 'get_init_context',
 'get_input_embeddings',
 'get_memory_footprint',
 'get_output_embeddings',
 'get_parameter',
 'get_parameter_or_buffer',
 'get_position_embeddings',
 'get_submodule',
 'gradient_checkpointing_disable',
 'gradient_checkpointing_enable',
 'half',
 'init_parallel_plans',
 'init_weights',
 'initialize_weights',
 'input_modalities',
 'ipu',
 'is_backend_compatible',
 'is_custom_code',
 'is_gradient_checkpointing',
 'is_remote_code',
 'load_adapter',
 'load_state_dict',
 'loss_function',
 'main_input_name',
 'mark_tied_weights_as_initialized',
 'maybe_distribute_model',
 'model_tags',
 'modules',
 'mtia',
 'named_buffers',
 'named_children',
 'named_modules',
 'named_non_persistent_buffers',
 'named_parameters',
 'num_parameters',
 'parameters',
 'post_init',
 'pp_plan',
 'prepare_distribute_model',
 'push_to_hub',
 'register_backward_hook',
 'register_buffer',
 'register_for_auto_class',
 'register_forward_hook',
 'register_forward_pre_hook',
 'register_full_backward_hook',
 'register_full_backward_pre_hook',
 'register_load_state_dict_post_hook',
 'register_load_state_dict_pre_hook',
 'register_module',
 'register_parameter',
 'register_state_dict_post_hook',
 'register_state_dict_pre_hook',
 'requires_grad_',
 'resize_position_embeddings',
 'resize_token_embeddings',
 'retrieve_modules_from_names',
 'save_distributed_checkpoint',
 'save_pretrained',
 'set_adapter',
 'set_attn_implementation',
 'set_decoder',
 'set_encoder',
 'set_experts_implementation',
 'set_extra_state',
 'set_input_embeddings',
 'set_output_embeddings',
 'set_submodule',
 'set_use_kernels',
 'share_memory',
 'should_save_on_this_rank',
 'state_dict',
 'supports_context_parallel',
 'supports_gradient_checkpointing',
 'supports_pp_plan',
 'supports_tp_plan',
 'tie_weights',
 'to',
 'to_empty',
 'tp_plan',
 'tp_size',
 'train',
 'type',
 'use_kernels',
 'warn_if_padding_and_no_attention_mask',
 'xpu',
 'zero_grad']

In [32]:
train_encodings = tokenizer(list(train_reviews['reviews'].values),padding=True,truncation=True,return_tensors="pt").to(device)
valid_encodings =  tokenizer(list(validation_reviews['reviews'].values),padding=True,truncation=True,return_tensors="pt").to(device)
test_encodings =  tokenizer(list(test_reviews['reviews'].values),padding=True,truncation=True,return_tensors="pt").to(device)

In [33]:
type(train_encodings)

transformers.tokenization_utils_base.BatchEncoding

In [34]:
train_encodings.to(device)

{'input_ids': tensor([[  101,  2074, 12476,  ...,     0,     0,     0],
        [  101,  2204,  2204,  ...,     0,     0,     0],
        [  101,  2204,  2204,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2190,  ...,     0,     0,     0],
        [  101,  6429,  4031,  ...,     0,     0,     0],
        [  101,  2307,  2007,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [35]:
train_encodings['input_ids']

tensor([[  101,  2074, 12476,  ...,     0,     0,     0],
        [  101,  2204,  2204,  ...,     0,     0,     0],
        [  101,  2204,  2204,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2190,  ...,     0,     0,     0],
        [  101,  6429,  4031,  ...,     0,     0,     0],
        [  101,  2307,  2007,  ...,     0,     0,     0]])

In [36]:
print(train_encodings['attention_mask'][0].device)
train_encodings['input_ids'][0]

cpu

tensor([  101,  2074, 12476,  1045,  2293,  2023,  2201,  1012,  2009,  1005,
         1055,  2200,  2204,  1012,  2062,  2000,  1996,  5099,  6154,  2217,
         2084,  2014,  2783,  3769,  2614,  1012,  1012,  2061,  1044, 18863,
          999,  1045,  4952,  2000,  2023, 10126,  2012,  1996,  9726,   999,
         1045,  2507,  2009,  1019, 14117,  5790,  2035,  1996,  2126,  1012,
         2014, 19240,  2015,  2024,  2074,  4689,  1012,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0])

In [37]:
# tokenizer(x,padding=True,truncation=True)['input_ids']

In [38]:
# type(train_encodings['input_ids'])

In [39]:
class ReviewDataSet(torch.utils.data.Dataset):
    def __init__(self,encodings,sentiment):
        self.encodings = encodings
        self.sentiment = sentiment

    def __getitem__(self, index):
        item = {key:val[index] for key,val in self.encodings.items()}
        item['sentiment']=torch.tensor(self.sentiment[index]).to(device)

        return item

    def __len__(self):
        return len(self.sentiment)

In [40]:
train_df = ReviewDataSet(train_encodings,list(train_reviews['user_sentiment'].values))
valid_df = ReviewDataSet(valid_encodings,list(validation_reviews['user_sentiment'].values))
test_df = ReviewDataSet(test_encodings,list(test_reviews['user_sentiment'].values))

In [41]:
train_df[0]['input_ids'].device

device(type='cpu')

In [42]:
from torch.utils.data import DataLoader

In [43]:
len(train_df)

372

In [44]:
torch.accelerator.get_device_capability()

{'supported_dtypes': {torch.bfloat16,
  torch.bool,
  torch.complex32,
  torch.complex64,
  torch.float16,
  torch.float32,
  torch.int16,
  torch.int32,
  torch.int64,
  torch.int8,
  torch.uint16,
  torch.uint32,
  torch.uint64,
  torch.uint8}}

In [45]:
device = 'mps'

In [46]:
BATCH_SIZE = 32
train_loader = DataLoader(train_df,batch_size=BATCH_SIZE,shuffle=True)

In [47]:
val_loader = DataLoader(valid_df,batch_size=BATCH_SIZE,shuffle=False)

In [48]:
test_loader = DataLoader(test_df,batch_size=BATCH_SIZE,shuffle=False)

In [49]:
model

DistilBertTokenizer(name_or_path='distilbert-base-uncased', vocab_size=30522, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
})

In [50]:
len(train_loader)

12

In [51]:
len(train_df)

372

In [52]:
from transformers import DistilBertForSequenceClassification

In [53]:
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [54]:
model=model.to(device)

In [55]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [56]:
dir(model)

['T_destination',
 '__annotate_func__',
 '__annotations__',
 '__annotations_cache__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adjust_bias',
 '_adjust_missing_and_unexpected_keys',
 '_apply',
 '_auto_class',
 '_backward_compatibility_gradient_checkpointing',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_can_compile_fullgraph',
 '_can_record_outputs',
 '_can_set_attn_implementation',
 '_can_set_experts_implementation',
 '_can_set_experts_implementation_cached_value',
 '_check_and_adjust_attn_implementation',
 '_check_and_adjust_experts_implementation',
 '_compatible_flash_implementations',
 '_compiled_call_impl',
 '_copy_lm_head_original_to_resized',
 '_default_compile_config',
 '_device_mesh',
 '_dispatch_accelerate_model',
 '_ep_plan',
 '_ep_plan',
 '_finalize_model_loading',
 '_flash_attn_can_dispatch',
 '_flash_attn_import_error',
 '_flex_attn_can_dispatch',
 '_forward_hooks',
 '_forward_hooks_always_called',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_from_config',
 '_fsdp_plan',
 '_fsdp_plan',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_dtype_plan',
 '_get_files_timestamps',
 '_get_name',
 '_get_resized_embeddings',
 '_get_resized_lm_head',
 '_grouped_mm_can_dispatch',
 '_hf_peft_config_loaded',
 '_init_added_embeddings_weights_with_mean',
 '_init_added_lm_head_bias_with_mean',
 '_init_added_lm_head_weights_with_mean',
 '_init_weights',
 '_initialize_missing_keys',
 '_initialize_weights',
 '_input_embed_layer',
 '_is_full_backward_hook',
 '_is_hf_initialized',
 '_is_stateful',
 '_keep_in_fp32_modules',
 '_keep_in_fp32_modules',
 '_keep_in_fp32_modules_strict',
 '_keep_in_fp32_modules_strict',
 '_keys_to_ignore_on_load_missing',
 '_keys_to_ignore_on_load_missing',
 '_keys_to_ignore_on_load_unexpected',
 '_keys_to_ignore_on_load_unexpected',
 '_keys_to_ignore_on_save',
 '_keys_to_ignore_on_save',
 '_load_from_state_dict',
 '_load_pretrained_model',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_move_missing_keys_from_meta_to_device',
 '_named_members',
 '_no_split_modules',
 '_no_split_modules',
 '_non_persistent_buffers_set',
 '_parameters',
 '_pp_plan',
 '_pp_plan',
 '_prepare_peft_hotswap_kwargs',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_replicate_for_data_parallel',
 '_resize_token_embeddings',
 '_save_to_state_dict',
 '_sdpa_can_dispatch',
 '_set_gradient_checkpointing',
 '_skip_keys_device_placement',
 '_skip_keys_device_placement',
 '_slow_forward',
 '_state_dict_hooks',
 '_state_dict_pre_hooks',
 '_supports_attention_backend',
 '_supports_context_parallel',
 '_supports_flash_attn',
 '_supports_flex_attn',
 '_supports_sdpa',
 '_tied_weights_keys',
 '_tp_plan',
 '_tp_plan',
 '_tp_size',
 '_upload_modified_files',
 '_use_kernels',
 '_version',
 '_weight_conversions',
 '_wrapped_call_impl',
 'active_adapters',
 'add_adapter',
 'add_model_tags',
 'add_module',
 'all_tied_weights_keys',
 'apply',
 'barrier_after_gathered_checkpoint_save',
 'base_model',
 'base_model_prefix',
 'bfloat16',
 'buffers',
 'call_super_init',
 'can_generate',
 'can_record_outputs',
 'children',
 'classifier',
 'compile',
 'config',
 'config_class',
 'cpu',
 'cuda',
 'delete_adapter',
 'dequantize',
 'device',
 'disable_adapters',
 'disable_input_require_grads',
 'distilbert',
 'double',
 'dropout',
 'dtype',
 'dummy_inputs',
 'dump_patches',
 'enable_adapters',
 'enable_input_require_grads',
 'enable_peft_hotswap',
 'eval',
 'extra_repr',
 'float',
 'forward',
 'from_pretrained',
 'fsdp_plan',
 'gather_sharded_state_dict_for_save',
 'generation_config_class',
 'get_adapter_state_dict',
 'get_buffer',
 'get_compiled_call',
 'get_correct_attn_implementation',
 'get_correct_experts_implementation',
 'get_decoder',
 'get_encoder',
 'get_expanded_tied_weights_keys',
 'get_experts_implementation',
 'get_extra_state',
 'get_init_context',
 'get_input_embeddings',
 'get_memory_footprint',
 'get_output_embeddings',
 'get_parameter',
 'get_parameter_or_buffer',
 'get_position_embeddings',
 'get_submodule',
 'gradient_checkpointing_disable',
 'gradient_checkpointing_enable',
 'half',
 'init_parallel_plans',
 'init_weights',
 'initialize_weights',
 'input_modalities',
 'ipu',
 'is_backend_compatible',
 'is_custom_code',
 'is_gradient_checkpointing',
 'is_remote_code',
 'kernel_config',
 'load_adapter',
 'load_state_dict',
 'loss_function',
 'loss_type',
 'main_input_name',
 'mark_tied_weights_as_initialized',
 'maybe_distribute_model',
 'model_tags',
 'modules',
 'mtia',
 'name_or_path',
 'named_buffers',
 'named_children',
 'named_modules',
 'named_non_persistent_buffers',
 'named_parameters',
 'num_labels',
 'num_parameters',
 'parameters',
 'post_init',
 'pp_plan',
 'pre_classifier',
 'prepare_distribute_model',
 'push_to_hub',
 'register_backward_hook',
 'register_buffer',
 'register_for_auto_class',
 'register_forward_hook',
 'register_forward_pre_hook',
 'register_full_backward_hook',
 'register_full_backward_pre_hook',
 'register_load_state_dict_post_hook',
 'register_load_state_dict_pre_hook',
 'register_module',
 'register_parameter',
 'register_state_dict_post_hook',
 'register_state_dict_pre_hook',
 'requires_grad_',
 'resize_position_embeddings',
 'resize_token_embeddings',
 'retrieve_modules_from_names',
 'save_distributed_checkpoint',
 'save_pretrained',
 'set_adapter',
 'set_attn_implementation',
 'set_decoder',
 'set_encoder',
 'set_experts_implementation',
 'set_extra_state',
 'set_input_embeddings',
 'set_output_embeddings',
 'set_submodule',
 'set_use_kernels',
 'share_memory',
 'should_save_on_this_rank',
 'smart_apply',
 'state_dict',
 'supports_context_parallel',
 'supports_gradient_checkpointing',
 'supports_pp_plan',
 'supports_tp_plan',
 'tie_weights',
 'to',
 'to_empty',
 'tp_plan',
 'tp_size',
 'train',
 'training',
 'type',
 'use_kernels',
 'warn_if_padding_and_no_attention_mask',
 'xpu',
 'zero_grad']

In [57]:
for p,m in model.named_parameters():
    print(p,m.shape)

distilbert.embeddings.word_embeddings.weight torch.Size([30522, 768])
distilbert.embeddings.position_embeddings.weight torch.Size([512, 768])
distilbert.embeddings.LayerNorm.weight torch.Size([768])
distilbert.embeddings.LayerNorm.bias torch.Size([768])
distilbert.transformer.layer.0.attention.q_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.0.attention.q_lin.bias torch.Size([768])
distilbert.transformer.layer.0.attention.k_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.0.attention.k_lin.bias torch.Size([768])
distilbert.transformer.layer.0.attention.v_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.0.attention.v_lin.bias torch.Size([768])
distilbert.transformer.layer.0.attention.out_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.0.attention.out_lin.bias torch.Size([768])
distilbert.transformer.layer.0.sa_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.0.sa_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.0.ffn.lin1.weight torch.Size([3072, 768])
distilbert.transformer.layer.0.ffn.lin1.bias torch.Size([3072])
distilbert.transformer.layer.0.ffn.lin2.weight torch.Size([768, 3072])
distilbert.transformer.layer.0.ffn.lin2.bias torch.Size([768])
distilbert.transformer.layer.0.output_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.0.output_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.1.attention.q_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.1.attention.q_lin.bias torch.Size([768])
distilbert.transformer.layer.1.attention.k_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.1.attention.k_lin.bias torch.Size([768])
distilbert.transformer.layer.1.attention.v_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.1.attention.v_lin.bias torch.Size([768])
distilbert.transformer.layer.1.attention.out_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.1.attention.out_lin.bias torch.Size([768])
distilbert.transformer.layer.1.sa_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.1.sa_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.1.ffn.lin1.weight torch.Size([3072, 768])
distilbert.transformer.layer.1.ffn.lin1.bias torch.Size([3072])
distilbert.transformer.layer.1.ffn.lin2.weight torch.Size([768, 3072])
distilbert.transformer.layer.1.ffn.lin2.bias torch.Size([768])
distilbert.transformer.layer.1.output_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.1.output_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.2.attention.q_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.2.attention.q_lin.bias torch.Size([768])
distilbert.transformer.layer.2.attention.k_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.2.attention.k_lin.bias torch.Size([768])
distilbert.transformer.layer.2.attention.v_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.2.attention.v_lin.bias torch.Size([768])
distilbert.transformer.layer.2.attention.out_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.2.attention.out_lin.bias torch.Size([768])
distilbert.transformer.layer.2.sa_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.2.sa_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.2.ffn.lin1.weight torch.Size([3072, 768])
distilbert.transformer.layer.2.ffn.lin1.bias torch.Size([3072])
distilbert.transformer.layer.2.ffn.lin2.weight torch.Size([768, 3072])
distilbert.transformer.layer.2.ffn.lin2.bias torch.Size([768])
distilbert.transformer.layer.2.output_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.2.output_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.3.attention.q_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.3.attention.q_lin.bias torch.Size([768])
distilbert.transformer.layer.3.attention.k_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.3.attention.k_lin.bias torch.Size([768])
distilbert.transformer.layer.3.attention.v_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.3.attention.v_lin.bias torch.Size([768])
distilbert.transformer.layer.3.attention.out_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.3.attention.out_lin.bias torch.Size([768])
distilbert.transformer.layer.3.sa_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.3.sa_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.3.ffn.lin1.weight torch.Size([3072, 768])
distilbert.transformer.layer.3.ffn.lin1.bias torch.Size([3072])
distilbert.transformer.layer.3.ffn.lin2.weight torch.Size([768, 3072])
distilbert.transformer.layer.3.ffn.lin2.bias torch.Size([768])
distilbert.transformer.layer.3.output_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.3.output_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.4.attention.q_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.4.attention.q_lin.bias torch.Size([768])
distilbert.transformer.layer.4.attention.k_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.4.attention.k_lin.bias torch.Size([768])
distilbert.transformer.layer.4.attention.v_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.4.attention.v_lin.bias torch.Size([768])
distilbert.transformer.layer.4.attention.out_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.4.attention.out_lin.bias torch.Size([768])
distilbert.transformer.layer.4.sa_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.4.sa_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.4.ffn.lin1.weight torch.Size([3072, 768])
distilbert.transformer.layer.4.ffn.lin1.bias torch.Size([3072])
distilbert.transformer.layer.4.ffn.lin2.weight torch.Size([768, 3072])
distilbert.transformer.layer.4.ffn.lin2.bias torch.Size([768])
distilbert.transformer.layer.4.output_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.4.output_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.5.attention.q_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.5.attention.q_lin.bias torch.Size([768])
distilbert.transformer.layer.5.attention.k_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.5.attention.k_lin.bias torch.Size([768])
distilbert.transformer.layer.5.attention.v_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.5.attention.v_lin.bias torch.Size([768])
distilbert.transformer.layer.5.attention.out_lin.weight torch.Size([768, 768])
distilbert.transformer.layer.5.attention.out_lin.bias torch.Size([768])
distilbert.transformer.layer.5.sa_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.5.sa_layer_norm.bias torch.Size([768])
distilbert.transformer.layer.5.ffn.lin1.weight torch.Size([3072, 768])
distilbert.transformer.layer.5.ffn.lin1.bias torch.Size([3072])
distilbert.transformer.layer.5.ffn.lin2.weight torch.Size([768, 3072])
distilbert.transformer.layer.5.ffn.lin2.bias torch.Size([768])
distilbert.transformer.layer.5.output_layer_norm.weight torch.Size([768])
distilbert.transformer.layer.5.output_layer_norm.bias torch.Size([768])
pre_classifier.weight torch.Size([768, 768])
pre_classifier.bias torch.Size([768])
classifier.weight torch.Size([2, 768])
classifier.bias torch.Size([2])

In [58]:
model.train()

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [59]:
optim = torch.optim.AdamW(model.parameters(),lr=.003)

In [60]:
x = torch.tensor([1])

In [61]:
torch.manual_seed(RANDOM_SEED)

In [103]:
torch.mps.seed()

In [104]:
torch.backends.cudnn.deterministic=True

torch.backends.cudnn.benchmark = True

In [105]:
torch.use_deterministic_algorithms(True)

In [106]:
import random
random.seed(RANDOM_SEED)
np.random.seed(0)

In [107]:
#torch.manual_seed(0)
torch.argmax(torch.randn(4,4),dim=1).to(device)

tensor([0, 2, 0, 1], device='mps:0')

In [108]:
device

'mps'

In [109]:
@torch.compile()
def compute_accuracy(model, data_loader, device):
    print(model)
    with torch.no_grad():
        correct_pred, num_examples = 0, 0

        for batch_idx, batch in enumerate(data_loader):
            ### Prepare data
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["sentiment"].to(device)
            outputs = model(input_ids, attention_mask=attention_mask)
            logits = outputs["logits"]
            predicted_labels = torch.argmax(logits, 1)
            num_examples += labels.size(0)
            correct_pred += (predicted_labels == labels).sum()
            print(f"{num_examples=},{correct_pred=}")
        return correct_pred.float() / num_examples * 100

In [110]:
x = next(iter(train_loader))

In [111]:
x['input_ids']

tensor([[ 101, 2187, 2026,  ...,    0,    0,    0],
        [ 101, 3492, 2204,  ...,    0,    0,    0],
        [ 101, 2307, 2005,  ...,    0,    0,    0],
        ...,
        [ 101, 6919, 2005,  ...,    0,    0,    0],
        [ 101, 2065, 2017,  ...,    0,    0,    0],
        [ 101, 2200, 4138,  ...,    0,    0,    0]])

In [112]:
# import os
# os.environ['PYTORCH_MPS_HIGH_WATERMARK_RATIO']='0.0'
# os.environ["PYTORCH_MPS_HIGH_WATERMARK_RATIO"] = "0.0"

In [113]:
len(train_loader)

12

In [73]:
import time
start = time.time()
from tqdm import tqdm

for epoch in range(1):
    model.train()
    for index,data in enumerate(tqdm(train_loader,desc=f"Training at {epoch}")):

        ### Prepare Data
        input_ids,attention_mask = data['input_ids'],data['attention_mask']
        sentiment = data['sentiment'].to(device)
        #print(input_ids,attention_mask)
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)

        #print(sentiment)
        ### Forward Pass
        outputs = model(input_ids,attention_mask=attention_mask,labels=sentiment)
        #print("Hi")
        loss,logits = outputs['loss'],outputs['logits']
        #print(loss)
        ### Backward Pass
        optim.zero_grad()
        loss.backward()
        optim.step()
        #print("Bye")
        ### Logging
        print(index)
        if not index%250:
            print(
                    f"Epoch: {epoch + 1:04d}/{NUM_EPOCHS:04d} | "
                    f"Batch {index:04d}/{len(train_loader):04d} | "
                    f"Loss: {loss:.4f}"
                )
    model.eval()

    with torch.set_grad_enabled(False):
            #print("Fuck")
            print(
                f"Training accuracy: "
                f"{compute_accuracy(model, train_loader, device):.2f}%"
                f"\nValid accuracy: "
                f"{compute_accuracy(model, val_loader, device):.2f}%"
            )

    print(f"Time elapsed: {(time.time() - start) / 60:.2f} min")


print(f"Total Training Time: {(time.time() - start) / 60:.2f} min")

Training at 0:   0%|          | 0/12 [00:00<?, ?it/s]

0

Training at 0:   8%|▊         | 1/12 [00:01<00:21,  1.94s/it]

Epoch: 0001/0003 | Batch 0000/0012 | Loss: 0.7023
1

Training at 0:  25%|██▌       | 3/12 [00:02<00:07,  1.18it/s]

2

Training at 0:  33%|███▎      | 4/12 [00:03<00:06,  1.18it/s]

3

Training at 0:  42%|████▏     | 5/12 [00:04<00:05,  1.19it/s]

4

Training at 0:  50%|█████     | 6/12 [00:05<00:05,  1.19it/s]

5

Training at 0:  58%|█████▊    | 7/12 [00:06<00:04,  1.20it/s]

6

Training at 0:  67%|██████▋   | 8/12 [00:07<00:03,  1.19it/s]

7

Training at 0:  75%|███████▌  | 9/12 [00:07<00:02,  1.19it/s]

8

Training at 0:  83%|████████▎ | 10/12 [00:08<00:01,  1.20it/s]

9

Training at 0:  92%|█████████▏| 11/12 [00:09<00:00,  1.20it/s]

10

Training at 0: 100%|██████████| 12/12 [00:10<00:00,  1.11it/s]

11

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/_dynamo/utils.py:4415: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)  # type: ignore[operator]
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/interpreter.py:377: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return target(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/experimental/proxy_tensor.py:2014: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return func(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/_dynamo/utils.py:4415: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)  # type: ignore[operator]
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/interpreter.py:377: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return target(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/experimental/proxy_tensor.py:2014: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return func(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/_dynamo/utils.py:4415: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)  # type: ignore[operator]
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/interpreter.py:377: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return target(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/experimental/proxy_tensor.py:2014: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return func(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/_dynamo/utils.py:4415: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)  # type: ignore[operator]
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/interpreter.py:377: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return target(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/experimental/proxy_tensor.py:2014: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return func(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/_dynamo/utils.py:4415: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)  # type: ignore[operator]
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/interpreter.py:377: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return target(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/experimental/proxy_tensor.py:2014: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return func(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/_dynamo/utils.py:4415: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)  # type: ignore[operator]
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/interpreter.py:377: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return target(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/experimental/proxy_tensor.py:2014: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return func(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/_dynamo/utils.py:4415: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)  # type: ignore[operator]
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/interpreter.py:377: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return target(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/experimental/proxy_tensor.py:2014: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return func(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/_dynamo/utils.py:4415: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return node.target(*args, **kwargs)  # type: ignore[operator]
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/interpreter.py:377: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return target(*args, **kwargs)
/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/fx/experimental/proxy_tensor.py:2014: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return func(*args, **kwargs)
W0924 16:28:36.937000 2597 torch/_dynamo/convert_frame.py:2008] [2/8] torch._dynamo hit config.recompile_limit (8)
W0924 16:28:36.937000 2597 torch/_dynamo/convert_frame.py:2008] [2/8]    function: '__getitem__' (/var/folders/3y/b0yw6xl90r5ddg0z2yylh2380000gn/T/ipykernel_2597/3169158636.py:6)
W0924 16:28:36.937000 2597 torch/_dynamo/convert_frame.py:2008] [2/8]    last reason: 2/7: index == 318  # item['sentiment']=torch.tensor(self.sentiment[index]).to(device)  # ar/folders/3y/b0yw6xl90r5ddg0z2yylh2380000gn/T/ipykernel_2597/3169158636.py:8 in __getitem__ (_dynamo/variables/tensor.py:2849 in evaluate_expr)
W0924 16:28:36.937000 2597 torch/_dynamo/convert_frame.py:2008] [2/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W0924 16:28:36.937000 2597 torch/_dynamo/convert_frame.py:2008] [2/8] To diagnose recompilation issues, see https://docs.pytorch.org/docs/main/user_guide/torch_compiler/compile/programming_model.recompilation.html
W0924 16:28:37.682000 2597 torch/_inductor/utils.py:1806] [3/0] Not enough SMs to use max_autotune_gemm mode

num_examples=32,correct_pred=tensor(30, device='mps:0')
num_examples=64,correct_pred=tensor(59, device='mps:0')
num_examples=96,correct_pred=tensor(83, device='mps:0')
num_examples=128,correct_pred=tensor(110, device='mps:0')
num_examples=160,correct_pred=tensor(140, device='mps:0')
num_examples=192,correct_pred=tensor(168, device='mps:0')
num_examples=224,correct_pred=tensor(192, device='mps:0')
num_examples=256,correct_pred=tensor(217, device='mps:0')
num_examples=288,correct_pred=tensor(246, device='mps:0')
num_examples=320,correct_pred=tensor(270, device='mps:0')
num_examples=352,correct_pred=tensor(295, device='mps:0')
num_examples=372,correct_pred=tensor(310, device='mps:0')
DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)
num_examples=32,correct_pred=tensor(28, device='mps:0')
num_examples=64,correct_pred=tensor(59, device='mps:0')
num_examples=96,correct_pred=tensor(91, device='mps:0')
num_examples=128,correct_pred=tensor(122, device='mps:0')
num_examples=160,correct_pred=tensor(152, device='mps:0')
num_examples=192,correct_pred=tensor(179, device='mps:0')
num_examples=224,correct_pred=tensor(209, device='mps:0')
num_examples=256,correct_pred=tensor(238, device='mps:0')
num_examples=288,correct_pred=tensor(268, device='mps:0')
num_examples=320,correct_pred=tensor(297, device='mps:0')
num_examples=352,correct_pred=tensor(318, device='mps:0')
num_examples=373,correct_pred=tensor(328, device='mps:0')
Training accuracy: 83.33%
Valid accuracy: 87.94%
Time elapsed: 0.38 min
Total Training Time: 0.38 min

In [74]:
print(f"Test accuracy: {compute_accuracy(model, test_loader, device):.2f}%")

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)
num_examples=32,correct_pred=tensor(28, device='mps:0')
num_examples=64,correct_pred=tensor(60, device='mps:0')
num_examples=96,correct_pred=tensor(83, device='mps:0')
num_examples=128,correct_pred=tensor(109, device='mps:0')
num_examples=160,correct_pred=tensor(134, device='mps:0')
num_examples=192,correct_pred=tensor(163, device='mps:0')
num_examples=224,correct_pred=tensor(193, device='mps:0')
num_examples=256,correct_pred=tensor(217, device='mps:0')
num_examples=288,correct_pred=tensor(243, device='mps:0')
num_examples=298,correct_pred=tensor(248, device='mps:0')
Test accuracy: 83.22%

In [75]:
del model

In [76]:
import gc
gc.collect()

101905

In [77]:
torch.mps.driver_allocated_memory()

5788483584

In [78]:
torch.mps.empty_cache()

In [79]:
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [80]:
device = "mps"

In [81]:
model=model.to(device)

In [82]:
model

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [83]:
model.train()

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True, bias=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [84]:
optim = torch.optim.Adam(model.parameters(),lr=1e-05)

In [85]:


from transformers import Trainer,TrainingArguments

In [86]:
import evaluate

metric = evaluate.load("accuracy")

Downloading builder script: 0.00B [00:00, ?B/s]

In [87]:
result = metric.compute(
    predictions=[0, 1, 1],
    references=[0, 1, 0]
)

In [88]:
result

{'accuracy': 0.6666666666666666}

In [97]:
def compute_metric(eval_pred):
    print(eval_pred)
    logits,labels = eval_pred
    predictions = np.argmax(logits,axis=-1)
    return metric.compute(predictions=predictions,references=labels)

In [98]:
training_args = TrainingArguments(
    output_dir='./results/',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,

    logging_steps=10,

)

In [99]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_df,
    eval_dataset=valid_df,
    compute_metrics=compute_metric,
    optimizers=(optim,None)  # optim and learning rate scheduler
)

In [100]:
start = time.time()

In [101]:
dir(trainer)

['__backends',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_accelerator_args',
 '_clip_grad_norm',
 '_created_lr_scheduler',
 '_determine_best_metric',
 '_evaluate',
 '_finalize_training',
 '_finish_current_push',
 '_get_collator_with_removed_columns',
 '_get_dataloader',
 '_get_eval_sampler',
 '_get_grad_norm',
 '_get_learning_rate',
 '_get_num_items_in_batch',
 '_get_output_dir',
 '_get_train_sampler',
 '_has_mixed_mesh_grads',
 '_hp_search_setup',
 '_init_training_state',
 '_inner_training_loop',
 '_issue_warnings_after_load',
 '_load_best_model',
 '_load_callback_state',
 '_load_from_checkpoint',
 '_load_optimizer_and_scheduler',
 '_load_rng_state',
 '_load_scaler',
 '_loggers_initialized',
 '_loss_shifts_labels',
 '_maybe_log_save_evaluate',
 '_memory_tracker',
 '_mixed_mesh_grad_norm',
 '_mixed_mesh_grads',
 '_move_model_to_device',
 '_prepare_context_parallel_inputs',
 '_prepare_for_training',
 '_prepare_input',
 '_prepare_inputs',
 '_push_from_checkpoint',
 '_remove_unused_columns',
 '_report_to_hp_search',
 '_run_epoch',
 '_save',
 '_save_checkpoint',
 '_save_optimizer_and_scheduler',
 '_save_rng_state',
 '_save_scaler',
 '_set_signature_columns_if_needed',
 '_signature_columns',
 '_track_num_input_tokens',
 '_train_batch_size',
 '_tune_save_checkpoint',
 '_update_auto_batch_size',
 '_validate_args',
 '_wrap_model',
 'accelerator',
 'add_callback',
 'args',
 'autocast_smart_context_manager',
 'call_model_init',
 'callback_handler',
 'can_return_loss',
 'compute_loss',
 'compute_loss_context_manager',
 'compute_loss_func',
 'compute_metrics',
 'control',
 'create_accelerator_and_postprocess',
 'create_model_card',
 'create_optimizer',
 'create_optimizer_and_scheduler',
 'create_scheduler',
 'current_flos',
 'data_collator',
 'deepspeed',
 'eval_dataset',
 'evaluate',
 'evaluation_loop',
 'floating_point_ops',
 'gather_function',
 'get_batch_samples',
 'get_cp_size',
 'get_decay_parameter_names',
 'get_eval_dataloader',
 'get_learning_rates',
 'get_num_trainable_parameters',
 'get_optimizer_cls_and_kwargs',
 'get_optimizer_group',
 'get_sp_size',
 'get_test_dataloader',
 'get_total_train_batch_size',
 'get_tp_size',
 'get_train_dataloader',
 'hp_name',
 'hp_search_backend',
 'hub_model_id',
 'hyperparameter_search',
 'init_hf_repo',
 'is_deepspeed_enabled',
 'is_fsdp_enabled',
 'is_fsdp_xla_enabled',
 'is_fsdp_xla_v1_enabled',
 'is_fsdp_xla_v2_enabled',
 'is_in_train',
 'is_local_process_zero',
 'is_model_parallel',
 'is_world_process_zero',
 'label_names',
 'label_smoother',
 'log',
 'log_metrics',
 'lr_scheduler',
 'metrics_format',
 'model',
 'model_accepts_loss_kwargs',
 'model_init',
 'model_wrapped',
 'neftune_noise_alpha',
 'num_examples',
 'optimizer',
 'optimizer_cls_and_kwargs',
 'place_model_on_device',
 'pop_callback',
 'predict',
 'prediction_step',
 'preprocess_logits_for_metrics',
 'processing_class',
 'push_to_hub',
 'remove_callback',
 'save_metrics',
 'save_model',
 'save_state',
 'set_initial_training_values',
 'state',
 'store_flos',
 'train',
 'train_dataset',
 'training_step']

In [102]:
trainer.train()

/Users/deven/.virtualenvs/Machine_Learning_Algorithms/lib/python3.14/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  super().__init__(loader)

ValueError: The model did not return a loss from the inputs, only the following keys: logits. For reference, the inputs it received are input_ids,attention_mask.