In [1]:
# import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly

In [94]:
df = pd.read_csv("googleplaystore_v2.csv")

In [95]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [4]:
df[:100]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19000.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14000.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8700.0,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25000.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2800.0,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,All of the parking lot - National Park applica...,AUTO_AND_VEHICLES,4.0,1754,14000.0,"500,000+",Free,0,Everyone,Auto & Vehicles,"June 2, 2018",2.3.4,4.0 and up
96,Inquiry Fines and Debits of Vehicles,AUTO_AND_VEHICLES,4.4,2680,2200.0,"500,000+",Free,0,Everyone,Auto & Vehicles,"March 20, 2018",1.03,4.0.3 and up
97,Gas Station,AUTO_AND_VEHICLES,4.0,1288,4500.0,"100,000+",Free,0,Everyone,Auto & Vehicles,"April 21, 2018",2.17,4.0 and up
98,Hush - Beauty for Everyone,BEAUTY,4.7,18900,17000.0,"500,000+",Free,0,Everyone,Beauty,"August 2, 2018",6.10.1,5.0 and up
99,"ipsy: Makeup, Beauty, and Tips",BEAUTY,4.9,49790,14000.0,"1,000,000+",Free,0,Everyone,Beauty,"November 9, 2017",2.3.0,4.1 and up

In [5]:
df.index

RangeIndex(start=0, stop=10841, step=1)

In [96]:
df.sort_values(by="Rating", ascending=False)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,21516.529524,Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN
9511,Ek Bander Ne Kholi Dukan,FAMILY,5.0,10,3000.000000,"10,000+",Free,0,Everyone,Entertainment,"June 26, 2017",1.0.9,4.0 and up
10166,FA Player Essentials,SPORTS,5.0,7,68000.000000,100+,Free,0,Everyone,Sports,"July 23, 2018",1.6.0,4.0.3 and up
7895,Dine In CT - Food Delivery,SHOPPING,5.0,4,1600.000000,"1,000+",Free,0,Everyone,Shopping,"May 16, 2016",1.3,4.0 and up
5118,Eternal Light AG,SOCIAL,5.0,30,13000.000000,100+,Free,0,Teen,Social,"May 19, 2018",1.04,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10824,Cardio-FR,MEDICAL,NaN,67,82000.000000,"10,000+",Free,0,Everyone,Medical,"July 31, 2018",2.2.2,4.4 and up
10825,Naruto & Boruto FR,SOCIAL,NaN,7,7700.000000,100+,Free,0,Teen,Social,"February 2, 2018",1.0,4.0 and up
10831,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38,9800.000000,"5,000+",Free,0,Everyone,Maps & Navigation,"June 13, 2018",2.0.148.0,4.0 and up
10835,FR Forms,BUSINESS,NaN,0,9600.000000,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9500.000000,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up

In [78]:
df.sort_values(by=["Rating", "Reviews"], ascending=False)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9496,Master E.K,FAMILY,5.0,90,21516.529524,"1,000+",Free,0,Everyone,Education,"August 11, 2017",1.5.0,4.4 and up
5245,AJ RETAILS,SHOPPING,5.0,9,169.0,10+,Free,0,Everyone,Shopping,"June 1, 2018",18060104,2.2 and up
9008,DW Timer,TOOLS,5.0,9,1500.0,100+,Free,0,Everyone,Tools,"April 5, 2017",1.0,1.6 and up
9188,EB Scanner,PRODUCTIVITY,5.0,9,25000.0,50+,Free,0,Everyone,Productivity,"February 11, 2018",1.7.8,4.0.3 and up
5795,Axe Champs! Wars,GAME,5.0,8,25000.0,50+,Free,0,Everyone,Arcade,"June 26, 2018",1.1,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10773,FQ India,LIFESTYLE,NaN,0,8900.0,10+,Free,0,Everyone,Lifestyle,"July 31, 2018",7.2.2,4.1 and up
10774,Miss FQ,NEWS_AND_MAGAZINES,NaN,0,36000.0,10+,Free,0,Everyone,News & Magazines,"April 5, 2018",3.8,4.4 and up
10798,Word Search Tab 1 FR,FAMILY,NaN,0,1020.0,50+,Paid,$1.04,Everyone,Puzzle,"February 6, 2012",1.1,3.0 and up
10822,PLMGSS FR,PRODUCTIVITY,NaN,0,3100.0,10+,Free,0,Everyone,Productivity,"December 1, 2017",1,4.4 and up
10835,FR Forms,BUSINESS,NaN,0,9600.0,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up

In [79]:
df["Installs"].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0', np.float64(21516.529524330235)],
      dtype=object)

In [16]:
df["Category"].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION',
       '1.9'], dtype=object)

In [17]:
x = "Life Made WI-Fi Touchscreen Photo Frame"

In [80]:
app = df.loc[10472]

In [81]:
print(app)

App               Photo Editor & Candy Camera & Grid & ScrapBook
Category                                                    None
Rating                                                       1.9
Reviews                                                     19.0
Size                                                        3.0M
Installs                                            21516.529524
Type                                                        Free
Price                                                          0
Content Rating                                          Everyone
Genres                                                       NaN
Last Updated                                   February 11, 2018
Current Ver                                               1.0.19
Android Ver                                           4.0 and up
Name: 10472, dtype: object

In [43]:
app1 = pd.Series(app.iloc[0], app.iloc[2:])

In [45]:
app.iloc[0]

'Life Made WI-Fi Touchscreen Photo Frame'

In [47]:
df.loc[10472].shift()

In [83]:
df.loc[10472][1:].shift(1, axis=0)

x = df.loc[10472].shift(1, axis=0)

In [66]:
df.loc[10472] = df.loc[10472][1:].shift(1, axis=0)  # Correct in morning...#todo

/var/folders/lj/nxvzwr3x3b9bfrgtmp4tfjjw0000gn/T/ipykernel_18748/4133570013.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.9' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[10472]=df.loc[10472][1:].shift(1,axis=0)
/var/folders/lj/nxvzwr3x3b9bfrgtmp4tfjjw0000gn/T/ipykernel_18748/4133570013.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '3.0M' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[10472]=df.loc[10472][1:].shift(1,axis=0)

In [57]:
sample_col = ["col1", "col2", "col3", "col4", "col5"]
sample_data = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
]
sample = pd.DataFrame(data=sample_data, columns=sample_col)
m = [0, 1, 2, 1]

In [76]:
df.loc[10472, "Rating"] = float(1.9)

In [69]:
df.loc[10472]["App"] = "Photo Editor & Candy Camera & Grid & ScrapBook"

/var/folders/lj/nxvzwr3x3b9bfrgtmp4tfjjw0000gn/T/ipykernel_18748/595042678.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[10472]['App']='Photo Editor & Candy Camera & Grid & ScrapBook'

In [58]:
marr = np.array(m)
for i in sorted(set(m)):
    if i == 0:
        continue
    sample.loc[marr == i] = sample.loc[marr == i].shift(i, axis=0)

In [72]:
df.loc[10472, "App"] = "Photo Editor & Candy Camera & Grid & ScrapBook"

   col1  col2  col3  col4  col5
0   1.0   2.0   3.0   4.0   5.0
1   NaN   NaN   NaN   NaN   NaN
2   NaN   NaN   NaN   NaN   NaN
3   6.0   7.0   8.0   9.0  10.0

In [84]:
x

App                                                  None
Category          Life Made WI-Fi Touchscreen Photo Frame
Rating                                                1.9
Reviews                                              19.0
Size                                                 3.0M
Installs                                     21516.529524
Type                                                 Free
Price                                                   0
Content Rating                                   Everyone
Genres                                                NaN
Last Updated                            February 11, 2018
Current Ver                                        1.0.19
Android Ver                                    4.0 and up
Name: 10472, dtype: object

In [88]:
x[2]

/var/folders/lj/nxvzwr3x3b9bfrgtmp4tfjjw0000gn/T/ipykernel_18748/658830076.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  x[2]

'1.9'

In [89]:
data = pd.DataFrame(
    np.arange(16).reshape((4, 4)),
    index=["Ohio", "Colorado", "Utah", "New York"],
    columns=["one", "two", "three", "four"],
)

In [90]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [91]:
data.drop(index=["Ohio", "Colorado"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [93]:
df["Reviews"].mean(skipna=True)

TypeError: Could not convert string '1599678751021564496716717836815137911211388087884482943261518553632271942162243994506547699611181922026020313622311202275035101535356481453663915859111717629522122062617453110708584536715982841705712954210479805129140339715347774388462431609029519040211356525301169861379271920736702119773735749941971361421516821551385414217773482501337278803617480665786314335097175426801288189004979011501739320902225436985729644205010417934601361871823013474113715359593157538268341192277228065418497735364184733066387125762291472418574478577550814080246315454060155446418224862031301435116507143323390468860363934967878731750618622084473031908016185842783191615462021336268751778270964513834252713221680273910652337572878851269301051561143411571612967473012547308518532584217730709911002861165891489454458622728941463531279184880736700015987230847188841116229591240344596414955690331614230551902320737212253808371060074359822808052287416214760232439897880805424922868971037554650511442102951598722962931370991515071802138323175586821115448415920815786627149307958006989164221087413161462416619770230869895211105878172159872296293137099151507180213832317558682111544841592081578662714930795800698916422897880804424922868971037554650511442102952177301002859515104132317510136352400557106224951683410102389703024387339144218193965144612088314256711519422551298392795643871330167775711512599521881421155198135961006596848955664284769119316125257964299514290354604324341924911334799158679307502841879986593954785892666023020936901514985419294899559437674136982473509207693688017103163543454876153812451083330535387333364812013666242370781810312825020832375413894670229391376125855640751177129222502127187691193165664657847859881224981133497334194331320148323959472853874461048416931285092451093171031287650078181028238335646350154349384346982244863107902893307613732012842860254652736893158803469809643041307511822649165413892473693429255150471251113036484801771485013100271565509811335011257810965182471906131252328323911334973720652754010499017770317529177263237468322544835655524416030845728393825322831528720573914873782020994984604483418814288427305218183374209011225951243468378422554142044706237073419513478598859472811335255104841695387446292081910323501542448631079028925465271545570042516801285726766462556777961637126323137244884530570831320172460419511633102123705366713202286711157212626222888206716431053414421941180619992254497684251911461304617268872295325935377852212197235206516419392778082540035109313541816012212570812416398678885355084243028572648845255677798371263261637537711633313724738305708953463122288817268516449534195286712126261439164513204853337130495169892315461491981354202254587232317013890570835371344014310598946191221215081802183520524395023651521576670140039742187250618298686618593528125185611033538422027762101401130024023051806120500001114140110401431011202400064954954256059310212105214219728651681263341605821832433185803535125791110532347882569158245318298611579769986289924181893254485375314299776977032346407510611932156065142861331362469362123901090266948342918748172640611619316829855673670058895741275721085298881929151621530142325451911079038537518189321185699020904813238124891224855521530127214556897859941185299803043581190422251223849902073404127332518352743617495570419277136123786218372656240275137913692236317694307563963316642105822778537518189362905072118569048199020223843238017250569493859911078844118579732669355695142632629050755256172508547984815751123364611079033143002065279348381647847161952062839232418352525828211856200058123970210861369498148550629050738475525684309481517250811079482669481420620653293481470042828402093786214056949814854984311211856206532172508256079207816103112131085352854562081165628948296771470089109399850952412250810291716536248856461419806979466181030781768237000175528182828434923684116469164076987029753245823549611661653008230638738441168389185014982133296296901305496130591633682420502646218673273265300824374726391511445505014975456208781310332442152541552343100661221638808992058881854933338712327927424608412970628815014807319692612012299812398359286444822378501498545659929682931009588185388089920581232793196916084128815016372580283338761201736864297062742419683527935931148071724787723185231821031977748674545670829677158082388089310066123279881853196917813608416530082742433387407719288150115033229976120180129706274241239835279359312237814807197774867489683034077197321856507251232792437471575623899412366667554387691601643771256664787177378240113707421532608920611811155585733782323089387446473169880099304566432005839466316106531346195312429814910011399528250171244243904152306367184264427808260761126563357383190620672957973130582312181671683442815247484453551812185367462199613837112073111632250706706301649596597415103927215255086044938178810697347838318043856199684445451336246257574932831230481881191945957347838126431215701345642831696111125477315928157036148861866223130699731311265872417706302105425166129304198703596161440751446106151417144241026054743442280842809168081575052464719223334106585749378361259413868135952110668188459623486137580281485685126447129304378015192595015993590577316597601462710982898707821126410099734787432903410909648795125071951040124729783064331313745492084636998145323956478432997822707129737611136611824731097843320616810384121074138031559441015928008436144553771398103293532405151080225139004258316850919314213143022473145414952125017261406555649256507117071077465399066196222071196278618812129126891359220151315693198622875170719024248396051122846415594419202287510329354011651517769032113437551045042800933320835218116403375172929695114204281561577380983113927233722012540059220098117925548021482764710361270570646564462381440405122735741719982759791162071502947086741140232153147091202918735162880270267559186777778642501144186112032991157211481018366227393104454947948482081232846910040620529966791183669399009542013010425153428951600961065471341952498552739670871010975638343190247827651115721755717076921072654016081907479767586288548226102628945115061288682611145019543233243116897756354997076921074828626652712692030193691561452032612955268132573841024029645594075702421873523121838626161285834356506791694352429926762327396708710755711171767041615674144022702941440501004061411631836692515342895118735205592625011447087536939582765327439249024094185393061229210205473405217789532606132418735206939527439249012601724094205472292142469306118539340527029432606217789513241873523693951439426540181213724102534642165704822620161289450381150631665205299137991114551114625763423324385761168977563707694179073167273861622436591324977600037711175293174353799275814377573848110054101173918935227141936857391231465312230131142874435438004281750849116022584408724961033052669107619126273224810809328014782382445051535380044652427663111200689644353685784811622431752934179073834273877142122584353813812087583014592326487670075391268624814659297832907434544112372580363130272110911302520739658055170377506126572619196017083186713120145912263939910239452221378112671896847497601140995513571356539364728716114316168100116079815893985426072607438293357261453432774574194182145109446652167536521896194129663222523164303195557786942121736865543326434782667610671797367505203047376491476917734481067397243788957361658203043309987520878298348026808124523601663717979590468081245236016637179795905311422033153328301393789421195204213213118034946410097285881962110544442750338334644473882772226422426677254258148897369203523416223133508811860910485308149736159800261052640669893778921619856310306448917231000417170396859811039314198297592068173226329524111356315566669129555727068721579305062754920817230056805713004908923587412873242053257724990491102165387614130760628988182921233817671249277231934447346104853341419860244891723224284564066980319786513510685418675988190814889518892501838462307102953056198880215793054656245985415344662313477514891223767249511372715062752610622990586103548118937492112218985655067761427110434523482513850932698348112501798826395566805746735387639275041012956064611379469269305444879114986482772409422428456135108936063011372671420034476724955234810607433481189371000417592282153508481188801042492523072737023422244981232126211825314152970226225101230253157638491146416946926719648256642777325825553801481773715656184106110168627544717475545784761453531499373531458371427019555829940230727419752166752311785165888541144110731029168189773337752102107309335842079240416325067074735881715403389572147771006091343866168717549720189962509493033120592187972484981205573539590175829186211992221119741218125107951300438207939433791344498822242971638835891420055027191421107197371627893159516592814801892468063309176807338446434214819522466584126325519021821252420455547456844165401660159017305748122451426247224301884449910142018912772535261990951049314894513517711889582231367354489388876144154067651295576599071046010486018811915112956253093932230849988336752352943198176100555214129665215858050659354196769907235925042189211382399883806197540746955566889269888215359731489246989238187674252112543829445655145492145154765691083571277253521500999423088681191545235294153597326988899906637674252211921813272651842101003269124285540142510979062515657955656337913146859172589754903915596502921645209621381820525517696194969327599381679910538547656910562037139147791347883343263216849354373753043430558067815338155930732512664921510393067642243018840676515990715006221420160428009814899015426426985112543853877818923847132726923043421451295625990796171448261068013006192123793218926074627104303556690814801822750645476441256474355211923521487881104015363495925041704415518611255665419676344942606514638163492140914686383445857614407234110486154706944214544499101477412753339832026757611161812948685977936937811436215048615382249361109974108795145510241014822869617320269194598431861611950428968286117163323366063286191021699746741530854705023590617753629440052060943232029420764968247149620267294361923011126236719652962629319179191991401411087716010366476445307921213723764046356169824450855869611021699748701152465206544076530904106750337854207587953235470311311146732032178175625850834843794151924565248777651008852555237621413634725841329192148295412732783925964306051408841867101484623060112080154895189543060525552623398472584666611044715741971917016960961881369295273198561075315428852345223328311008545601976318623772600729033617306332342761595879685596111233056697384382142481852195161535938021619069031315549641811605991710427338225333963802161906903131554964181160599171042733822533396445089018217347071359729133117108795472139553766660518386294397360285287451696098247144062392596796672076315742041233222931981266233985088763160131552873753079245579197203619701596193543842723212376564129603113557812963216171457172921153392199136112152063957915335773512141048452801015617857616825163325319133974342071217358726334920416251264114214665915819473731182752410285820942363303378825186742506266225374326574476156410200660992316083487837618538031838370731587418211891746691264531071070091415875503488190152686210008227721672160359945431878221847238896507349830521747451686529138857292113521189542752159295129218415545552121087363408171331972724852121533513815109012884303154519928346021612980395214175131686416882811292833634371713720631241070200932200620000000002503112304020423321000102801500001001451100010202094496874185374744101242014503211157307001630744330453241686531203596569102763026573123122315226122176236667253378611066651747172812921923160781583066657731386062594917329553262249217014787140343054414411894831125491913762608670616120076480271445225103331775476845719725562164042508796583741259075475160562226952209823132513223479908313633540930571461225339195833449217912983488441189378177031544138212041272538066691259849486824115700442310520580328581629553251380268936425317014705665774461483563883098724799091795517015352665773134305441515021064049583416373091259894115700316161019446122536715209593806669423138285820332493781770515041175794125989485245590006436777912983488695613382121207712175722205279130117581512598944868308524551064076378177090006462455742313852201833249791301416136210998591312942946087533896159166064414732788923973270909226157305485792335563858581067988820371862571444255108494518252427503656216741662287308343672902588162655386022512578317158424414156827314251210912413504310859213152424873230823417849768406601271945362183641586791892318711798997552896779397013151918199021373562110394287131590821020813707497926128472567071461531018831659997511798528961819905792028523249533725321020813707493375828472134207193117982788923528962278512139735970115582137351696618199057920621103912578341986441473186116130853159085916569285232856034171445884158105773909204279428335839420521020895520461536840618179825719142512278892339735512197011308528523445889420595520137074927889234602725961104252375130855917485354973878335836840644071621208139735638051231818231923298716109500211591320504243239810858556219745389531426342594501230299148042184152825781034985940289336249680337810525349265441918647447622185840182031163198544003337956116773158047125259561141570016523263612857884410585547090233039285781159058534211579287116880217306242110858538701898471592519519871665441852825582404755272473157936554276807024181353291601579287426771517369811693234403368649420792970715098357247189848650931060804494112927211106649553108590517018984715925195198716432961300814621521409178886049211351254157506187141611688024047542097334753635846781402418135244371128652153436120977336864675311548651074955316320852649149449152724881977433439351255477831187142133379521263376807124047537360615426714340145100014907322163282116323211468075176624181589149173158151759455910286371676528117141075277752986533687051579343937265970688231094865132495531972952157830745332896987175425613158151462702521138180228366282882459795133825911995173334290931908562701077241014551527802173341038427790291031112725763466393818678398781528676358012100313576317644819811601699923649012228221840112517214123248718093895023242316641391248618883469755104549910316106277900521138459795122282176448133825910312888094361152113882882910317844228880930173084036255752192309262610237167202079875431845130981904610611085338711151296732779045001763650176450501794361152114099711222831660361530524082133833910339903238610152114012228382883133833910333539432386288809288954103951154927790452114034123459797405755174272539997112228382883342912666521838765133833294310831875431867991033323866893580900288809551175545288955017911151308401605267136626219848520294919051506471321638848154560122601211830388178782687111628373594039235155219848337821926412338655751551247813286216101767792129689985851366334598515572168152277455622851162838256214432750708117882421800439351718892510371575027560481546150932928768833266651327548930430541830387156801698051123044716529962053459987212564252834427355603974221162837111821673448930304471366261003520313257402478142546692524281520281803927560227482163881698047780770533256481546145441348954808224191791561776103234893016092198481366263040321638833256481546186228258260133183038857573178781162837359560172022635251411489071534815465757392353731497236762120373402254284999715960182942129707386558033493574509318239241993733312759663308332164077028860766042618973932945838255923412623943304681136874123677906935375543155851421221512722396022415145483282501859115748191851366145528705517030128042325094357315163997543159124142011843959973321111147887040442958087686620770642548791115074729041154091663676189181926615420760571133579914850667991215269277311482111238885387335093423369083112718856591639580724265165757645488675568481909611163931545784067639833273283139480801054185910965597110732045941989442733511533926102879413420315693489794103036371210595949642858122554430907274744394113775336745245493413013756217299068309112180571466466641496571724139258327941029236702776758324215507315633114154529485142393716881148516220920247451210229832157834414739355525226726640164956863425413123713547244396032772092296626107962739942920318918205644066453398120892828646664189342495905867433049897890250375861762301372371591595120100130294701636241129775805212180118459112479694177338381574958648148498177724646664123901853307435771290241694881040128806113436673025807112180526640251210625161687300181399881407046249245114564784425919417435115773120082084126536926301629711881542731171822622879432528962264561079491112009653586751038306287250480643278006914742131538398526559135008550186131023089694985820881598110245156403115072193021488396657257705910923676187982096961498393153681234121856328084727649644141854997321260111795525370741461768734046171027015599956713117255691474298843725131488396205191736951448795383971497946091829795301527779467523174152084125273121130163052264564963991079616815974549900618796150813748064085822724456724010175703312321122424215078058137204106432262955790469147440461014883972988541559994806385157898516349302912598510270608401335732339319805110259485823080119269192731211267189103830368501861309186691642016149714322824608617941763614343114133936378967107559497632484492936238616210029949834336907316319046471763750511501692715349378066031982466681940341025334653432479703182152839767951558437159455205340489298199511118178934112971537018194406061333383690013120374184100994200081342618773269417457135337762314228582140421431893138986830961734782434922154174931596623322934467772634184252565530575575908915511276454807259003121916400393010320762392421933817624197382596051869998819530064369213511681615596906384348456395048232592255559218686449158742093264212689369694574471466511920264744266685011549288351320512611215647467215962216996538630249919158196426242641129678129706306938355860662930805425635592137882190888948198954810711190818505869721297887763551684175110116674033579447352543188183028731504139502114741490209044274700629594016756807128401743321038241399966978663841770332121350744258776351310281284017849573311231581380492591858844097527104247992636476105307222967815652424790131696169224991936841897663020627404925976677293080781544795942017371166740323330580368232922967812479024991923641368413217189764925963020409751724029308025668062465636472017378776431030741310281284018723262915681534811048005045943269564434928420142188436521262821411018710220632864541592265229768102248412251620492601453562105622158936822909379371586563920383751665730141320605160946559032225443482327912572705561240564716939102186174771688188571183860838170001661623358864183720995123982133401805398949891048314138156141024773055658562634541728557394801311148852365453997174864210923374257435763014548277117031221896152658147661852384353342672089305369109672960726170347957416841042128466509917987636946985183897146854508679207871077985226760131184136091013465111721290852530576515466898324279314769825623548133195129529317069145088462532078744111741515240492752926585763491877624406951371987812820822191563745152769833106112495512996800234942194466114184910159507992062303988971305050155304214210291625834487182126682948177129228360715428284891005318681528024819472247283253412304488144723125280222482997834946241397944289022419455272759642112153187373404901110121888557238742916526686809649960824707376109432751778921451130452411545955132027306498361002138206459626197177730534740829217361051021486250914482588730208323742299778116142640974305868749722309511591129140261860844101386776270676574902586261911711076243406486898734701530110158414771811689594000433236823384492142651878927401544327884605210819491063773537879515067833075096106577368241354408256475995141316571735081415114882891520927156324951843009361485361819831625746601476759518584246043241037492316135911055210534600359062007399400566428478595964142903889443513024551127263213548394357214116579722588111760