In [1]:
import numpy as np
import pandas as pd
import statsmodels as sm

In [3]:
df = pd.read_csv("Advertising.csv")

In [4]:
df.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [12]:
auto = pd.read_fwf("../../../datasets/islp/Auto.data")

In [13]:
auto.head()

  mpg\tcylinders\tdisplacement\thorsepower weight\tacceleration\tyear\torigin\tname
0  18.0   8   307.0      130.0      3504.      12...
1  15.0   8   350.0      165.0      3693.      11...
2  18.0   8   318.0      150.0      3436.      11...
3  16.0   8   304.0      150.0      3433.      12...
4  17.0   8   302.0      140.0      3449.      10...

In [14]:
from ISLP import load_data

auto_data = load_data("Auto")

In [15]:
auto_data

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin
name,,,,,,,,
chevrolet chevelle malibu,18.0,8,307.0,130,3504,12.0,70,1
buick skylark 320,15.0,8,350.0,165,3693,11.5,70,1
plymouth satellite,18.0,8,318.0,150,3436,11.0,70,1
amc rebel sst,16.0,8,304.0,150,3433,12.0,70,1
ford torino,17.0,8,302.0,140,3449,10.5,70,1
...,...,...,...,...,...,...,...,...
ford mustang gl,27.0,4,140.0,86,2790,15.6,82,1
vw pickup,44.0,4,97.0,52,2130,24.6,82,2
dodge rampage,32.0,4,135.0,84,2295,11.6,82,1
ford ranger,28.0,4,120.0,79,2625,18.6,82,1
chevy s-10,31.0,4,119.0,82,2720,19.4,82,1

In [16]:
auto_data.to_csv("Auto.csv")

In [17]:
df

     Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [19]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [20]:
df

        TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [21]:
from scipy import stats

In [22]:
stats.norm.ppf(0.975)

np.float64(1.959963984540054)

Summary

Summary  In this session, you built a simple linear regression model in Python using the advertising dataset. You also saw some more theoretical aspects in between. Here's a brief of what you learnt in this session.
1. A quick recap of simple linear regression
2. Assumptions of simple linear regression
    * Linear relationship between X and y.
    * Normal distribution of error terms.
    * Independence of error terms.
    * Constant variance of error terms.
3. Hypothesis testing in linear regression
    * To determine the significance of beta coefficients.
    * H0:β1=0;HA:β1≠0. 
    * T-test on the beta coefficient.
    * t score=^βiSE(^βi).
4. Building a linear model
    * OLS (Ordinary Least Squares) method in statsmodels to fit a line.
    * Summary statistics
        * F-statistic, R-squared, coefficients and their p-values.
5. Residual Analysis
    * Histogram of the error terms to check normality.
    * Plot of the error terms with X or y to check independence.
6. Predictions
    * Making predictions on the test set using the 'predict()' function.
7. Linear Regression using SKLearn
    * A second package apart from statsmodels for linear regression.
    * A more hassle-free package to just fit a line without any inferences.
Rahim has also answered some common doubts surrounding linear regression. This part has also been included in the notebook provided to you at the beginning of the session.